### PR TITLE
add support for netgear switch

### PR DESCRIPTION
**Pull request by aschaber1**
tested with netgear m5300 series switch
unfortunately reading config requires enable..

### CODE REVIEW

**Comment by ytti** [comment]
Same comments are your other model. The telnet method seems unused, you don't seem to specify telnet password/username prompt, so telnet wouldn't work anyhow. 

Is there no way to disable pager in netgear?

Also you need to send the enable password with ```cmd``` not ```send```, because ```cmd``` will wait for a prompt, ```send``` won't, and this will cause problems.

**Comment by ytti** [comment]
bump

**Comment by bbrendon** [comment]
I'd like to use this on a Prosafe m4100 . Any idea how? If I provided some details about how the login process worked, could someone create the expect script or whatever it is that oxidized uses?

**Comment by aschaber1** [comment]
@ytti if this looks better, I can rebase it of you'd like..

**Comment by bbrendon** [comment]
```
For this hostname:
current regex doesn't match: ^(\([\w-]+\)\s[#>])$
This does match :            ^(\([\w-+]+\)\s[#>])$
```

**Pull request merged**
