### PR TITLE
Nested Group Support

### PR DESCRIPTION
**Pull request by davama**
Hello this is for requested enhancement on #396 . Having nested group using /

I'm not really sure if i did this PR correctly. I understand you would not be able to accept the changes of my fork. Just forked it to create this ticket.

Please let me know if there's any info needed from me.

Thanks!
Dave

### CODE REVIEW

**Comment by ytti** [comment]
Unsure if I actually want to document this as supported, since if it works, it kinda works on accident.  Code doesn't really support subgroups.

**Comment by davama** [comment]
>  it kinda works on accident

:D 

i guess the only issue is [this](https://github.com/ytti/oxidized/issues/471#issuecomment-226234994) cannot see on api because of the /

**Comment by ytti** [comment]
I'm pretty sure there are other issues, but that's at least one issue.

**Comment by davama** [comment]
I understand the concerns.

So i guess at this point this is an accidental "partially" working feature with no hopes for official support.... at this time at least :-)

**Comment by ytti** [comment]
I think this would be good feature, but I don't see personally working towards it. If someone else does, grand. 
If I ever get around rewriting the core, support like this probably would come in as a side effect to that work.

**Comment by laf** [comment]
@davama Proposing that we close as this is just a doc change but wouldn't be officially supported.

**Comment by davama** [comment]
Agreed, closing

**Comment by laf** [comment]
Thanks very much.

**Pull request closed without merging**
