### PR TITLE
Line wrapping

### PR DESCRIPTION
**Pull request by davama**
Issues seen on procurve devices

Never really done a PR before so not sure if this is the right way to do it.

But this is related to issue #496 

Is this something we can do?

Thanks
Dave

### CODE REVIEW

**Comment by ytti** [comment]
Does it fix #496? Does ```0``` fix it?

**Comment by davama** [comment]
Yes, it fixed #496.
No, `:char_wide=>0` did not fix it.
Thanks

**Comment by ytti** [comment]
I am not super comfortable accepting this. I think I need to make this so, that model ```config :ssh```can set this.

**Comment by davama** [comment]
Understand the concern. 
Setting it on the config file would probably make more sense.

**Comment by davama** [comment]
Willing to test...

**Comment by ytti** [comment]
I hope to have something within a week

**Comment by davama** [comment]
Thanks!

**Comment by davama** [comment]
Hello @ytti , anything?
no rush

**Comment by ytti** [comment]
I've forgotten this, thanks for pinging me.

**Comment by ytti** [comment]
Can you check https://github.com/ytti/oxidized/commit/98ee2d2fadd56b9efadfc4f9ff667f71f6b22f6c - completely untested.

**Comment by davama** [comment]
https://github.com/ytti/oxidized/commit/98ee2d2fadd56b9efadfc4f9ff667f71f6b22f6c worked!

dont know all the backend details that need to be done but hopefully it get's merged soon

Thanks!!

Close?

**Comment by ytti** [comment]
Will close, thanks for testing.

**Pull request closed without merging**
