### PR TITLE
EdgeCOS: include transceiver details

### PR DESCRIPTION
**Pull request by freddy36**
## Pre-Request Checklist

- [X] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [X] Tests added or adapted (try `rake test`)
- [X] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
add support for transceiver details in the EdgeCOS model

### CODE REVIEW

**Comment by wk** [comment]
Seeing that much of the information produced by the command appears to be scrubbed, it appears to be that the intention is to identify the type of optics in place - does EgdeCOS perhaps offer some form of 'show hardware' or 'show inventory' command that would produce this information as part of its output, but without generating the volatile information often produced by inspecting DOM optics?

**Comment by freddy36** [comment]
@wk there are no such EdgeCOS commands.
There's no other command of getting the transceiver details.

**Comment by wk** [comment]
This looks okay as-is, although for clarity, it might be better to remove the values rather than the entire line (as a user simply viewing the output collected by oxidized may not immediately understand why only some of the output has been collected).

Let me know if you are willing to work on this or if you'd like it to go in in it's current version.

**Comment by freddy36** [comment]
@wk updated the patch to hide the values as suggested

**Comment by wk** [comment]
Great! Thank you. Let's pull this in.

**Pull request merged**
