### PR TITLE
Add new model for A10 Networks TPS

### PR DESCRIPTION
**Pull request by alexandrecorso**
## Description
Add a new model for A10 Networks TPS (https://www.a10networks.com/products/ddos-protection-thunder-tps)

### CODE REVIEW

**Comment by ytti** [comment]
There isn't telnet support in this model, as there insn't username/password prompt. I'd remove the :telnet tag.
The prelogout seems fragile, I'd recommend replacing it with multiple ```cmd``` which each expect some regexp, either default (prompt) or defined regexp.

**Comment by wk** [comment]
Hi! Thanks for submitting this.

I notice that this model is largely similar to the `acos.rb` model, with support for partitions removed and a number of additional / different strings cleaned away as secrets and from `show version`. This suggests that both devices run the same OS type (`ACOS`).

What is the motivation for splitting this specific device into its own dedicated model instead of integrating the changes into `acos.rb`?

**Comment by alexandrecorso** [comment]
Hello
A10 Networks TPS is using ACOS software. 
```
tps03# show version
Thunder Series Unified Application Service Gateway TH7445
    ...
     64-bit Advanced Core OS (ACOS) version 3.2.3-P3, build 3 (Mar-03-2019,20:04)
```

TPS is different too (it is not a load balancer). Some commands are not good on TPS.
```
tps03#show partition-config all
                            ^
% Unrecognized command.Invalid input detected at '^' marker.

tps03#show running-config all-partitions
                                   ^
% Unrecognized command.Invalid input detected at '^' marker.
```
Alexandre

**Comment by wk** [comment]
@alexandrecorso could you take a look at #1760 and see if the changes suggested there also work in your use case, and how can they be reconciled into supporting all of these devices under one model?

**Comment by alexandrecorso** [comment]
From my point of view, we need 2 templates. Some commands like this one, 
```
tps01.ams9.ams#show partition-config all
                             ^
% Unrecognized command.Invalid input detected at '^' marker.
```
doesn't works as in #1760

**Comment by edielson** [comment]
i have an A10 th1040 CGNAT

when using configure it in oxidized I have the following error:

Apr 12 11:06:19 host.myrouter.com.br oxidized [15551]: 10.200.0.1 raised Timeout :: Error with msg "execution expired"
Apr 12 11:06:39 host.myrouter.com.br oxidized [15551]: 10.200.0.1 raised Oxidized :: PromptUndetect with msg "unable to detect prompt: (? -Mix: ^ ([- \ w. \ /: ? \ [\] ()] + [#>] \ s?) $) "
Apr 12 11:06:39 host.myrouter.com.br oxidized [15551]: a10tps / QNETFACIL-A10 status no_connection, retry attempt 1
Apr 12 11:07:05 host.myrouter.com.br oxidized [15551]: 10.200.0.1 raised Timeout :: Error with msg "execution expired"



in file router.db

QNETFACIL-A10:10.200.0.1:a10tps:a10tps

**Comment by mortzu** [comment]
Please process the checklist

**Pull request closed without merging**
