### PR TITLE
Create linuxgeneric.rb model

### PR DESCRIPTION
**Pull request by davama**
See: https://github.com/ytti/oxidized/issues/1818

View [culumus.rb](https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/cumulus.rb) for differences

I have tested it with CentOS 7. It worked fine. :smile: 

I am not too sure how to feel about the `prompt`. 

To to reiterate here, for more specific needs, users could extend the model like so:

```
require 'oxidized/model/linuxgeneric.rb'

class LinuxGeneric
  
  cmd :secret, clear: true do |cfg|
    cfg.gsub! /^(username (\S+) privilege (\d+) (\S+) (\d+)).*/, '\\1 <redacted>'
    cfg
  end
   
  post do
    cfg = add_comment 'THE MONKEY PATCH'
    cfg += cmd 'firewall-cmd --list-all --zone=public'
  end
end

```

Any input is much appreciated!

Thank you,
Dave

### CODE REVIEW

**Comment by wk** [comment]
This looks interesting; much like the dnsdig model in #1669, it's equal parts interesting and unexpected to see something like this find a use case, but the context seems to be addressed in the related issue.

This PR could benefit from:
* A model notes file, which includes at least the comment above
* CHANGELOG.md entry
* Supported-OS-Types.md entry

**Comment by davama** [comment]
Thank you for the input @wk 

That is an interesting PR; i would say that it is much like this one. although that one looks more complicated and specific; i guess to capture the whole ZONE.

I will do as you noted.

Thank you

**Comment by davama** [comment]
I have done as suggested.

I still plan to add more notes and test with Ubuntu and Debian for completeness
I'll update when done.

Thank you

**Comment by wk** [comment]
This looks like a considerable amount of progress, @davama! It looks basically ready to go in. 

While I maintain there are better-suited tools for this particular task (and recovery from a single text blob will be, at best, inconvenient) - it seems to fill two niches nicely:
* Oxidized testing without real equipment (this model could be used as part of unit tests and ran against a Linux docker container or similar).
* Troubleshooting local installations (by targeting, for example, the Oxidized host itself as the only node with the expectation that it's a good known state host which will succeed).

@ytti, what are your thoughts here?

**Comment by wk** [comment]
@davama - I've discussed this in short with @ytti out of the issue, and there is no objections to this being pulled. If you wish, we can pull it in as-is today. With that said:
* `iptables` is not a package that's installed or available out of the box in all distributions
* `/etc/ntp.conf` relies on a specific version of ntpd being installed, not a common default
* `/etc/snmp/snmpd.conf` relies on snmpd being installed, not a common default

It might be helpful to document the assumptions being made (in terms of distribution, packages present, ...) for the model to behave in a predictable manner.

**Comment by wk** [comment]
Please let us know how you'd like to proceed here.

**Comment by davama** [comment]
Points noted!
I want this to be a basic as possible.
I can simply remove them if need be.
Also, havent gotten around to trying with Unbunt/Debian. 

So ill report when this is ready to go.

Thank you,
Dave

**Comment by davama** [comment]
@wk 
It has been quite busy for me, unfortunately I still have not been able to have time to test with other OSes...

I dont want my slowness to stop the progress of this.
I think you can merge as is. If complaints then we can address then.

Please let me know if there are any questions.

Thank you,
Dave

**Comment by wk** [comment]
Pulling this in as requested; please be aware that the `SNMP settings` block also likely relies on a package that's not present by default in a minimal install of the distribution. A PR for this would be welcome.

**Pull request merged**
