### PR TITLE
Procurve: add gsub and update show power-supply command

### PR DESCRIPTION
**Pull request by davama**
Could be a solution to https://github.com/ytti/oxidized/issues/1453

Tested the gsub with the following possible outputs:
```
Power Supply Status: 

  Member  PS#   Model     Serial      State           AC/DC  + V        Wattage   Max   
  ------- ----- --------- ----------- --------------- ----------------- --------- ------
  1   J8712A    Powered         AC 120V/240V      875
  1   J8712A    Powered         AC 120V/240V      875
   2   J8712A    Not Powered     AC 120V/240V        0
   2   J8712A    Not Powered     AC 120V/240V        0
   2   Unknwn    Not Present                         0 
  1       1     JL085A    CN75GZ83SY  Powered         AC 120V/240V        48       250
  1       2     JL085A    CN75GZ840B  Powered         AC 120V/240V        34       250
  2       1     JL085A    CN75GZ83U4  Powered         AC 120V/240V        47       250
  2       2     JL085A    CN75GZ8625  Powered         AC 120V/240V        33       250
  3       1     JL085A    CN79GZ82G2  Powered         AC 120V/240V        21       250
  3       2     JL085A    CN79GZ82CQ  Powered         AC 120V/240V        25       250
 1     J9580A    TH42DMN0MR  Powered          AC 120V/240V       70      1000
 2     J9580A    TH42DMN074  Powered          AC 120V/240V       78      1000
```

Here is some diffs:

```
 ! 
-! 
 ! Power Supply Status: 
-! 
 !  PS#    Model       State        AC/DC  + V      Wattage
 !  ---- --------- ------------- ----------------- ---------
-!   1   J8713A    Powered         AC 120V           875
-!   2   J8713A    Powered         AC 120V           875
-! 
-!    2 /  2
-!    Total power:  1750 W
-! 
+!    1   J8713A    Powered         AC 120V
+!    2   J8713A    Powered         AC 120V 
 ! 
```
```
 ! 
-!
 ! Power Supply Status: 
-!
 ! PS#    Model       State        AC/DC  + V      Wattage
 ! ---- --------- ------------- ----------------- ---------
-!   1   J8713A    Powered         AC 120V           875
-!   2   Unknwn    Not Present                         0 
-!
-!   1 /  2 supply bays delivering power.
-!   Total power: 875 W
-! 
+!    1   J8713A    Powered         AC 120V
+!    2   Unknwn    Not Present          
 !                
```

Let me know if something is missing.

Thanks,
dave

### CODE REVIEW

**Comment by lst123** [comment]
Thank you. It helps.

**Comment by davama** [comment]
@lst123
Thank you for the feedback!
Glad it works

**Comment by BenKennish** [comment]
I'm having the problem of the wattage being reported and therefore Oxidized generating new commits for a device every time it changes.  Can this PR please be accepted so that I can use the next release of Oxidized (I'm currently installing using `gem install oxidized:0.22.0`).  Thanks

**Comment by davama** [comment]
@BenKennish 
You could create your own module  https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md that way it never matters when a PR for a specific module is merged. As long as you have the `gsub` it will be fine. See https://github.com/ytti/oxidized/issues/1384 if you need ideas

**Comment by BenKennish** [comment]
Thanks @davama.  I'm not familiar with Ruby but I will give it a go.

**Comment by BenKennish** [comment]
I've tried leaving this as `~/.config/oxidized/model/procurve.rb` ...

```
require 'oxidized/model/procurve.rb'

class Procurve

  # all this is based upon the following pull request:  https://github.com/ytti/oxidized/pull/1553

  cmd 'show system power-supply | in Power|Not P|Model|---' do |cfg|
    comment cfg
  end

  cmd :secret do |cfg|

    # copied and pasted from the original procurve.rb
    cfg.gsub! /^(snmp-server community).*/, '\\1 <configuration removed>'
    cfg.gsub! /^(snmp-server host).*/, '\\1 <configuration removed>'
    cfg.gsub! /^(radius-server host).*/, '\\1 <configuration removed>'
    cfg.gsub! /^(radius-server key).*/, '\\1 <configuration removed>'

    # don't show certain PSU info
    cfg.gsub! /^(\s+((\d+\s+){2}|\d+\s+)\w+\s+(\w+\s+(Powered|Present)|Powered)\s+(AC\s+\S+|\s+)).*/, '\\1'

    cfg

  end

end
```

Some of the diffs for our procurve devices have now started returning:
`+! Invalid input: power-supply`
whereas others seem to have added lines like this...

```
+! Power Supply Status: 
+! ----+--------------+------------------+------------+------ 
+!   1 | Powered      |  AC 120V/220V    | 103        | 800       
+!   2 | Not Present  |  -- ---------    | 0          | 0       
```
.. so it seems to be returning more power supply info, not less.

What I'm trying to do is suppress the config dump of power supply information for these procurve devices - we don't need this in our backup and it's creating a new commit for us every time the wattage changes.

Sorry to be a pain but I have zero Ruby experience so I'm kind of stabbing in the dark and don't know where to go from here.  Thanks in advance for any help you might be able to provide.

**Comment by davama** [comment]
Looks like you on the right track. Your output does not match the gsub since it’s a different way of displaying the power supplies...HP for ya *eyeroll*

If thats the case then you have several options:

1. Removed the power cmd block from the procurve.rb distribution file (would have to redo after every update
2. Copy existing distribution model to .configs/blabla and remove the block 
3. Using extended model from the link, replace the cmd block with own cmds you want to run
4. Remove power cmd from model all together. Would need PR
5. Update your gsub so that it works with your power supply output

Hope this helps.

**Comment by thanegill** [comment]
What would it take to get this merged?

**Comment by wk** [comment]
Which of the commands generate the PSU output? The PSU output cleanup definitely does not belong in `:secret` (as it will not trigger for users who don't scrub secrets, nor is it a secret).

If there are many different variations of output and a lack of inventory of all of them, it might be easiest to just remove the offending information command completely from the model...

**Comment by davama** [comment]
https://github.com/ytti/oxidized/blob/1ad63fb18c66e9bd0f64d3d413268feeddd9af7c/lib/oxidized/model/procurve.rb#L52

Agreed it is not a `:secret` but thats the method that exist to clean it up and not get false config changes

If want to remove, that is find too since one can use their own custom modules to accomplish user needs

https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md

Thanks!

**Comment by Exordian** [comment]
I'd rather remove the command completely. I don't think the state of the power modules should be part of a configuration backup system. It's still possible to add this command by monkeypatching if it helps someone.

**Comment by davama** [comment]
@Exordian 
Thanks for the input

For “monkey renching” there is this https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md
Which i think should be used more than moding the actual rb model files, but not many know/do the extending models setup. It is much cleaner for sure.

I had originally submitted this PR addition before the knowledge of the extended setup. My org does not need this cmd in the original model now, so i have no feelings towards removing.

Others on the other hand will be affected if/when removed.

Please submit a PR for reversal. I have no say what gets accepted or not i just enjoy this product and contribute when i can.

Best,
Dave

**Pull request closed without merging**
