### PR TITLE
template for your PR

### PR DESCRIPTION
**Pull request by yuri-zubov**
@wk what do you think about a template for PR?
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

### CODE REVIEW

**Comment by wk** [comment]
Rubocop already runs as part of Travis CI, see [here](https://github.com/ytti/oxidized/blob/master/Rakefile#L12). This is redundant.

**Comment by yuri-zubov** [comment]
@wk what do you think about a template for PR?

**Comment by ytti** [comment]
I don't have strong opinion on either direction and happy with what ever result.

**Comment by yuri-zubov** [comment]
@wk, @ytti, @laf - the part of a template was taken from https://github.com/sensu-plugins/sensu-plugins-memory-checks/blob/master/.github/PULL_REQUEST_TEMPLATE.md
if you want you can extend this checklist

**Comment by laf** [comment]
I think this would need a bot coupled with it to check that people have confirmed they have gone through each of these otherwise it's just a burden on maintainers to chase for the info.

**Pull request closed without merging**
