### PR TITLE
Fix "unsafe_load" error

### LINKED ISSUE #2769: Error loading config: undefined method `unsafe_load' for Psych:Module
Hi, i get repeated errors loading config when i start the image i built of 0.29.1. 

 ✔ Container oxidized  Created                                                                                                                                                                                                       0.0s
Attaching to oxidized
oxidized  | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
oxidized  | *** Running /etc/my_init.d/10_syslog-ng.init...
oxidized  | Apr 26 11:54:18 076ea1cf96d2 syslog-ng[14]: syslog-ng starting up; version='3.35.1'
oxidized  | *** Booting runit daemon...
oxidized  | *** Runit started as PID 22
oxidized  | Apr 26 11:54:19 076ea1cf96d2 cron[28]: (CRON) INFO (pidfile fd = 3)
oxidized  | Apr 26 11:54:19 076ea1cf96d2 cron[28]: (CRON) INFO (Running @reboot jobs)
oxidized  | Error loading config: undefined method 'unsafe_load' for Psych:Module
oxidized  | Did you mean?  safe_load
oxidized  | Error loading config: undefined method 'unsafe_load' for Psych:Module
oxidized  | Did you mean?  safe_load

### PR DESCRIPTION
**Pull request by MattKobayashi**
## Pre-Request Checklist

- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [x] Tests added or adapted (try `rake test`)
- [x] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description

Fixes #2769

### CODE REVIEW

**Comment by mortzu** [comment]
Please add your change to CHANGELOG.md

**Comment by Jangsukwoo** [comment]
Great!

**Comment by mikenowak** [comment]
@MattKobayashi, would you be able to resolve the outstanding conflict so that this PR can progress?

**Comment by MattKobayashi** [comment]
Hi @mikenowak, the conflict has been resolved. Thank you!

**Pull request merged**
