### PR TITLE
added model for OneAccess OneOS Voice Gateways/Routers

### PR DESCRIPTION
**Pull request by crami**
Slight modifications to gemspec for newer ssh gem and correct telnet syntax

### CODE REVIEW

**Comment by ytti** [comment]
Why that Net::SSH version? If we're gonna move forward, we should go to 4.1 straight. We had specific reason to run 3.0.2, there was bug in newer ones, but /I Think/ it's fixed.

Please add the OneOS to README.md as well.

**Comment by crami** [comment]
Had Problems with the old version (3.0.2) connecting. 3.2 was the newest which worked without code change. Will Add OneOS to the Readme. Should I do a new or additional pull request?

**Comment by ytti** [comment]
You can add README.md change here. I'm not going to jump to 3.2, I don't know if it works, the issue did not affect everyone and every model. If we're gonna move forward, might as well go to 4.

**Comment by crami** [comment]
Tested again with net-ssh 3.0.2 and it works now with some config settings. So we can go with that unchanged.

**Comment by taro-75** [comment]
Hello,
I have a problem with router OneAccess: oneos6 when i use oneos.rb
My congif for Oxidized work fine with Cisco router
i can't connect Oneaccess Router:
raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^([\w.@()-]+#\s?)$)"

When can i find the regex on my router model plz ?

    show version
    Software version : ONEOS6-ADVIP_11N-V5.2R1E2_HA1
    Software created on : 04/03/15 17:03:22

Thank You
@taro-75

**Pull request merged**
