### PR TITLE
Refresh Dockerfile

### LINKED ISSUE #1204: Pushing to Github using ssh stopped working
Hi,

I have had oxidized up and running in a docker container since January and it was happily pushing configs up to Github. Nothing changed with the configuration or the Github ssh key exists and the container has had no restarts. 

The last time a configuration was pushed to Github was 22 February 2018. This coincidences with when Github removed weak cryptographic standards. See https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/

In the logs `Rugged::SshError: failed to start SSH session: Unable to exchange encryption keys>) for event :post_store` is the error

```
Mar  9 10:27:27 oxidized-2618625911-7mzjq oxidized[17]: Configuration updated for routers/ct-office
Mar  9 10:27:27 oxidized-2618625911-7mzjq oxidized[17]: GithubRepo: Pushing local repository(/root/.config/oxidized/git-repo/routers.git/)...
Mar  9 10:27:27 oxidized-2618625911-7mzjq oxidized[17]: GithubRepo: to remote: git@github.com:Telecom/infrastructure-backups.git
Mar  9 10:27:27 oxidized-2618625911-7mzjq oxidized[17]: Hook push_to_remote (#<GithubRepo:0x0000000001510120>) failed (#<Rugged::SshError: failed to start SSH session: Unable to exchange encryption keys>) for event :post_store
Mar  9 10:27:27 oxidized-2618625911-7mzjq oxidized[17]: SlackDiff: Connecting to slack
Mar  9 10:27:28 oxidized-2618625911-7mzjq oxidized[17]: SlackDiff: Connected
Mar  9 10:27:28 oxidized-2618625911-7mzjq oxidized[17]: SlackDiff: Posting diff as snippet to #private-core
Mar  9 10:27:29 oxidized-2618625911-7mzjq oxidized[17]: SlackDiff: Finished
```

Config (was working for over a month)

```
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: 
      routers: git@github.com:Telecom/infrastructure-backups.git
    privatekey: /root/.config/oxidized/git_id_rsa
    publickey: /root/.config/oxidized/git_id_rsa.pub
```

There are other libraries which are struggling with this issue - https://github.com/saltstack/salt/issues/46159

I was wondering if anyone else has experienced a similar issue?

I am not familiar with ruby so I am struggling to debug but will keep trying and update if I find anything.

### PR DESCRIPTION
**Pull request by wk**
Refresh Dockerfile to resolve multiple issues:
* Bump base image from 0.9.18 to 0.10.0 (now xenial based).
* Remove dependency on ppa:brightbox and use xenial ruby2.3
* Split build into 2 stages to backport libssh2 1.7.0 which is
  needed for githubrepo hook but is not available in xenial
* Misc cleanup and comments

This is meant to supersede #1039 by taking a more elegant approach, and closes #1204

### CODE REVIEW

**Comment by wk** [comment]
Might be worth noting explicitly: these Dockerfile modifications utilize the [multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/) feature and as a consequence depend on docker 17.05.0-ce (2017-05-04).

**Comment by yeled** [comment]
I wonder if the docker version will lock out some users of older setups?

**Comment by wk** [comment]
The docker 17.05.0-ce (2017-05-04) dependency is only for the build stage, the resulting container does run on older versions of docker. It is presumed that the primary deliverable resulting from this file is the oxidized/oxidized container on Docker Hub - but people who build their own on older docker versions may indeed be unpleasantly surprised.

**Comment by yeled** [comment]
Let's merge this into HEAD and warn people in the changelog

**Pull request merged**
