### PR TITLE
Initial OpenWrt support

### PR DESCRIPTION
**Pull request by z00nx**

### CODE REVIEW

**Comment by ytti** [comment]
I'm unsure about the vars use, maybe model vars should be prefixed with model name to create sort of namespace.

**Comment by wk** [comment]
Second that. @z00nx, would you consider renaming the `backup_partitions` knob to `openwrt_backup_partitions` to ensure you never unintentionally inherit configuration not intended for the model? There is precedent for this type of model namespacing in `comware.rb` and `fortios.rb`.

**Comment by z00nx** [comment]
@wk @ytti 
Thanks for the feedback. I'll update my pull request and rename the variable.

**Comment by z00nx** [comment]
I've renamed the variables and have made a few more options configurable

**Comment by wk** [comment]
@z00nx This looks ready. :+1: 
Created z00nx/oxidized#1 to add reference in supported model list and update changelog. Non-blocker.

**Comment by z00nx** [comment]
@wk merged the pull request. 👍

**Pull request merged**
