### PR TITLE
OpenBSD: Include bgpd, ospfd and ospf6d files

### PR DESCRIPTION
**Pull request by woopstar**
## Pre-Request Checklist
- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [x] Tests added or adapted (try `rake test`)

## Description
This will include the following files:
- bgpd.conf
- ospfd.conf
- ospf6d.conf

### CODE REVIEW

**Comment by woopstar** [comment]
How to re-trigger the CI? It does not look like the CI failure is code-wise.

**Comment by woopstar** [comment]
ping

**Comment by mortzu** [comment]
Please update the CHANGELOG file

**Comment by mortzu** [comment]
Still conflicts

**Pull request merged**
