### PR TITLE
Support for Dell EMC Networking OS9

### PR DESCRIPTION
**Pull request by baldoarturo**
## Pre-Request Checklist

- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [x] Tests added or adapted (try `rake test`)
- [x] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description

Added support for Dell EMC Networking OS9. This is "cisco like" but way different from OS10, so it needed a new model.

### CODE REVIEW

**Comment by mortzu** [comment]
Model looks mostly like the OS10 one. Do we need both of them?

**Comment by baldoarturo** [comment]
A separate model is not totally needed as OS9 can run the same set of commands for 
```
show inventory
show inventory media
show running-config
```

But, OS9 is a totally different software platform which does not share the same command line structure on other commands.

I guess that as long the user is aware of this, you can maybe map OS9 devices to use the OS10 model.

**Comment by mortzu** [comment]
Does your switch supports the command "show running-configuration" instead of "show running-config"?

**Comment by baldoarturo** [comment]
I just tested and `show running-configuration` works. So well maybe I am trying to reinvent the wheel on this.
Maybe it is enough by adding docs explaning that the OS10 model works for OS9 too. I can take care of that if you agree,

**Comment by mortzu** [comment]
Please

**Pull request closed without merging**
