### PR TITLE
New model for Asterfusion Network Operating System

### PR DESCRIPTION
**Pull request by avl-dev**
## Pre-Request Checklist

- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [x] Tests added or adapted (try `rake test`)
- [x] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description

model for Asterfusion Network Operating System (@avl-dev)

### CODE REVIEW

**Comment by mortzu** [comment]
Can you please fix the conflict

**Comment by avl-dev** [comment]
done!

**Comment by mortzu** [comment]
can you please fix the conflict?

**Comment by avl-dev** [comment]
done!

**Pull request merged**
