### PR TITLE
Added support for pfSense

### PR DESCRIPTION
**Pull request by stokbaek**
The prompt match is a mess due to colour/text format matching. If there exists a more simple way to match formatted text then please change it to be less messy.

### CODE REVIEW

**Comment by ytti** [comment]
Does it support ssh exec mode?

```
cfg :ssh do
  exec true
end
```

This means we're not doing screen-scraping for prompt for ssh.

**Comment by stokbaek** [comment]
pfSense is just a normal BSD machine really, so don't think it supports exec mode.

**Comment by ytti** [comment]
Normal OpenSSH does support exec.

This is exec: ```ssh server "command"``` it does not start shell channel at all, it runs exec channel with command as argument. If SSH implementation supports that, we can use it, which means we never need to do any screen-scraping for prompt.

**Comment by stokbaek** [comment]
pfSense does support this. I will create a new pull request with this instead.

**Pull request closed without merging**
