### PR TITLE
strip trailing lines in junos model if ssh_no_exec enabled

### PR DESCRIPTION
**Pull request by nickhilliard**
logic was the wrong way around, oops

### CODE REVIEW

**Comment by ytti** [comment]
Is it even needed though? I mean 'telnet' shouldn't return true, if we're on ssh, so that line shouldn't be ran on SSH, exec or no exec?

**Comment by nickhilliard** [comment]
it's needed due to ssh_no_exec being set in oxidized-script.

**Comment by nickhilliard** [comment]
the logic is:

- if you're logging in on telnet, the if-expression evaluates to true, so the lines are stripped
- if you're logging in via ssh with exec channels enabled, ssh_no_exec is set to false, so the if-expression evaluates to false, so the lines aren't stripped
- if you're logging in via ssh with exec channels disabled, ssh_no_exec is set to true, so the if-expression evaluates to true, so the lines are stripped

**Comment by ytti** [comment]
Right.  I guess we could also change the 'telnet' to 'screenscrape', and check it there.

Heck, perhaps we should provide 'screenscrape' method in model.rb, which is true if telnet or ssh with ssh_no_exec.
Then it could be just 'if screenscrape'

**Pull request merged**
