### PR TITLE
Add support for SLX-OS

### PR DESCRIPTION
**Pull request by mikaelmantel**
Add support for SLX-OS discuss on #1027 .

### CODE REVIEW

**Comment by laf** [comment]
Any reason you've left commented code in? May as well remove it if it's not needed.

Can you also update the https://github.com/ytti/oxidized/blob/master/docs/Supported-OS-Types.md file please to include this.

**Comment by mikaelmantel** [comment]
Done ;)

**Comment by laf** [comment]
Thanks :)

Last thing from me is the some indentation issues, you seem to be using some spaces and some tabs, can you replace with spaces please.

**Comment by mikaelmantel** [comment]
Ok sorry for that, it's good for you ?

**Comment by mikaelmantel** [comment]
any news ?

**Comment by mikaelmantel** [comment]
Thank you !

**Comment by laf** [comment]
No thank you :)

**Pull request merged**
