### PR TITLE
Fix edgeswitch model

### PR DESCRIPTION
**Pull request by JeanFrancoisMoule**
## Pre-Request Checklist

- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [x] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

### CODE REVIEW

**Comment by wk** [comment]
It seems that the goal of this change is to facilitate sending the user's own password as an `enable` password if `enable` isn't configured; this results in a rather unexpected behavior:
* If the user did not specify enable, enable is used anyway (but with user's own password)
* If the user did specify enable, the enable command is sent, but no password is sent afterwards.

A more consistent way to handle this could be:

```ruby
    # preferred way to handle additional passwords
    post_login do
      if vars(:enable) == true
        cmd "enable"
      elsif vars(:enable)
        cmd "enable", /^[pP]assword:/
        cmd vars(:enable)
      end
    end
```

The configuration will then need to specify the user's password both as password, and as the value of the enable field. This will result in the same outcome, but a more predictable behavior.

**Comment by wk** [comment]
@JeanFrancoisMoule @fadenb could you perhaps review if this can be done in a manner more similar to the standard way proposed above? We'd like to have a fix in, but for the right problem (not the lack of a correctly set 'enable' value for the node, but for the underlying behavior).

**Comment by Cormoran96** [comment]
With my EdgeSwitch 24 Lite
Os version 1.9.2. It doesn't work. I have message:

```
% Invalid input detected at &apos;^&apos; marker.
```

**Comment by mortzu** [comment]
Duplicate of #2234

**Pull request closed without merging**
