### PR TITLE
add bracket on node if using proxy and node has ipv6 address

### PR DESCRIPTION
**Pull request by davama**
Should solve: https://github.com/ytti/oxidized/issues/2228

Note:
Not a ruby dev so i am sure there is a better way to do it.
Open to suggestions.

I also tested if node has an ipv4 address and it also works. So basically, at least from what i can tell, it does not break anything. :laughing: 

Thanks,
Dave

### CODE REVIEW

**Comment by davama** [comment]
find it strange that Travis complains when the change is soo minor....

I think other projects on github were having travis issues recently....

**Comment by davama** [comment]
Sorry for the bump...

Just wanted to bring to the attention, since this change is literally the addition of two characters :smile: 
There is another proxy related PR which are very [interesting](https://github.com/ytti/oxidized/pull/2268). Hopefully it's merged soon too

Happy Friday!!

**Comment by ytti** [comment]
Apologies and thank you.

**Comment by davama** [comment]
@ytti 
No apologies needed here!
Thank you very much!!

have a good weekend

**Pull request merged**
