### PR TITLE
Added SG220 support to login prompt.

### PR DESCRIPTION
**Pull request by Atroskelis**
As per #1148 , SG220 has an unique login prompt, different than the rest.

This regex should cover both cases.

## Pre-Request Checklist

- [ ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [ ] Changes are reflected in the documentation
- [ ] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

### CODE REVIEW

**Comment by wk** [comment]
Hi there! As far as I can see, besides allowing the prompt to appear anywhere in the line rather than at the beginning - the modified username prompt regexp is actually stricter and does not introduce new cases. The modified password prompt also relaxes the match to include lowercase p ```password:```. 

Could you try if the following works for you instead, and if so, update your PR?

```ruby
username /^User ?[nN]ame:/
password /^\r?[pP]assword:$/
```

If it does not, it would be interesting to see a log of an interaction with an SG220 to understand what stray characters can be present before a prompt (```username /^\r?User ?[nN]ame:/``` might be a good guess).

**Comment by Atroskelis** [comment]
Hello!

I have to admit i was not so good at the regex, so i just found a valid pattern that worked for both cases. I did not bother or think it was efficient, so i expected someone to find a potential more efficient pattern, many thanks for that!

I shall test and update the PR.

**Comment by Atroskelis** [comment]
@wk 

Your code does not work.

SG220 still throws a 

` oxidized[24015]: 172.16.31.97 raised Oxidized::PromptUndetect with msg "#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012        Welcome to Layer 2 Managed Switch#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012#015#012  Press <Enter> to continue...#015#012#033[H#033[JUsername:  not matching configured prompt (?-mix:^\r?([\w.@()-]+[#>]\s?)$)"`

which definitely does not match /^User ?[nN]ame:/ due to characters before 'username'.

**Comment by wk** [comment]
@Atroskelis thank you for testing! 

I see it appears that the different SG models may or may not include a newline before the `Username` prompt, and some seem to emit telnet control codes instead. Matching the beginning of a line won't work here - how about a simple `username /User ?[nN]ame:/` instead in your use case? (note the removed `^`)

**Comment by Atroskelis** [comment]
@wk This regex pattern seems to work !

Alas, i'm not exactly sure how do do with the password, as i assumed it was the same with the username (just in case) . Nor the original nor the attempted altered version of yours /[Pp]assword:$/ worked. 

Debug showed like 

```
Connected to 172.16.31.209.
Username: cisco
cisco
Password: Trying 172.16.31.209...
Connected to 172.16.31.209.
Username: cisco
cisco
Password: Trying 172.16.31.209...
Connected to 172.16.31.209.
Username: cisco
cisco
```

My pushed variant for Password seems to work, though.

**Comment by Atroskelis** [comment]
Hello, 

For me without /(?:(?:Username:)|(?:(?:User\ Name\:))|(?:(?:User\ name\:)))/ it doesn't work

**Comment by ntokos** [comment]
Hello again.
I think the more generic username prompt that @wk proposed above and the removal of the dollar sign in the password prompt that I noted above should solve the login issues in SG220 switches.
@Atroskelis can you please try the following for login prompt in your ciscosmb.rb model file:
```
username /User ?[nN]ame:/
password /^\r?Password:/
```
This works perfectly well for my SG220 and SG550X Cisco SMB switches.

**Comment by Atroskelis** [comment]
Hello,

The proposed prompt syntax by @ntokos  apparently works. We can commit that one instead of the one i proposed.

**Comment by Atroskelis** [comment]
@wk  Fixed according to comments and tested functional, can be approved.

Thanks,

**Comment by wk** [comment]
Pulled this one in, thanks!

**Pull request merged**
