### PR TITLE
fix docker build

### PR DESCRIPTION
**Pull request by yeled**
fixes https://github.com/ytti/oxidized/issues/1180

### CODE REVIEW

**Comment by yeled** [comment]
@cstrock will you try this fix?

**Comment by laf** [comment]
Thanks for submitting this @yeled.

Testing your branch I get this:

```
docker build -q -t oxidized/oxidized:latest oxidized/
Sending build context to Docker daemon  13.16MB
Step 1/20 : FROM phusion/baseimage:0.9.18
 ---> 772dd063a060
Step 2/20 : MAINTAINER Samer Abdel-Hafez <sam@arahant.net>
 ---> Using cache
 ---> ecfff824c332
Step 3/20 : RUN add-apt-repository ppa:brightbox/ruby-ng && 	apt-get update &&   apt-get install -y ruby2.3 ruby2.3-dev libsqlite3-dev libssl-dev pkg-config make cmake libssh2-1-dev git g++ libffi-dev
 ---> Running in 4e0413a68576
The command '/bin/sh -c add-apt-repository ppa:brightbox/ruby-ng && 	apt-get update &&   apt-get install -y ruby2.3 ruby2.3-dev libsqlite3-dev libssl-dev pkg-config make cmake libssh2-1-dev git g++ libffi-dev' returned a non-zero code: 137
```

**Comment by cstrock** [comment]
Editing the dockerfile worked for me.  Thanks!

**Comment by yeled** [comment]
> Testing your branch I get this

Can you investigate that @laf a bit more? It's just an addition of one argument, and it works on @cstrock and my docker setup.

**Comment by laf** [comment]
Hmm very odd. I've just re-run it and it's worked this time :/

**Pull request merged**
