### PR TITLE
Add show commands to ciscosmb

### PR DESCRIPTION
**Pull request by davama**
Minor addition
Thanks!

### CODE REVIEW

**Comment by laf** [comment]
Could you post sanitized output for this ?

**Comment by davama** [comment]
Thank you for replying @laf 

Here is the output:
```
System Description:                       SF302-08P 8-Port 10/100 PoE Managed Switch
System Up Time (days,hour:min:sec):       05,22:59:06
System Contact:                           CDE
System Name:                              H-TXA-2WDM-SW-1
System Location:                          FTTX
System MAC Address:                       84:78:ac:a4:cc:79
System Object ID:                         1.3.6.1.4.1.9.6.1.82.8.2

Fans Status:                              N/A

```

Now looking at it...and seeing git... The `uptime` causes a lot of updates....how could I remove that line only?

**Comment by davama** [comment]
This could probably solve that part

```
    cfg.gsub! /System Up Time.*/, ''
```

**Comment by laf** [comment]
@davama Yes please, add that in and try it to make sure that it stops generating diffs and let me know when it's done :)

**Comment by davama** [comment]
Please let me know if anything else from my part

Thank you!

**Pull request merged**
