### PR TITLE
Fixed dependencies for net-ssh (#1742)

### PR DESCRIPTION
**Pull request by aneagoe**
## Description
Fixes dependencies for net-ssh when using ssh keys.
Closes issue #1742

### CODE REVIEW

**Comment by wk** [comment]
This looks good; surprising ed25519 adoption is sufficiently low that it took a few days since the update of the `net-ssh` dependency from 4.1 to 5.x for this to surface.

Could you add a change line to the `CHANGELOG.md` file as part of this PR before it's pulled in?

**Comment by aneagoe** [comment]
Will do it shortly. Also, it doesn't matter whether the key is ed25519 or plain rsa, this will still trigger.

**Comment by ytti** [comment]
The version specification seems too conservative compared to rest of our version specs.

**Comment by wk** [comment]
Per [net-ssh](https://rubygems.org/gems/net-ssh/versions/5.2.0), the actual dependencies are:

```
bcrypt_pbkdf ~> 1.0 
ed25519 ~> 1.2
```

@aneagoe any reason you've decided to narrow them further than this in your PR?

**Comment by aneagoe** [comment]
@wk I thought I took dependencies from the error output, but now I noticed a mismatch. I'll update this, sorry for the inconvenience.
```
oxidized_1  | net-ssh requires the following gems for ed25519 support:
oxidized_1  |  * ed25519 (>= 1.2, < 2.0)
oxidized_1  |  * bcrypt_pbkdf (>= 1.0, < 2.0)
```

**Comment by wk** [comment]
In this case, these are just two different ways to express the same thing, with the `~>` operator allowing to do so slightly more concisely.

**Comment by aneagoe** [comment]
@wk Right. Had no idea what twiddle:wakka was until now. I've fixed and pushed.

**Comment by wk** [comment]
New container with these changes in has been built at `oxidized/oxidized`, please confirm if this has resolved the issue in your case.

**Comment by aneagoe** [comment]
I just pulled and it all looks good. Would be great if version tags were added to dockerhub so I don't use latest in my configs. Thanks a lot for such a quick turnaround!

**Comment by ytti** [comment]
Docker does have versions, we've just not done release with this fix.

**Pull request merged**
