### PR TITLE
Cambium ePMP Support

### PR DESCRIPTION
**Pull request by martydingo**
## Description
Pull Request for Cambium ePMP devices to add support for these devices. The model name to use is cambiumepmp

I've had this running on our Oxidized instance and it's working well and perfectly stable for the last three months. 

This will close off https://github.com/ytti/oxidized/issues/2000 with people reporting that it works great in that issue. 

This will close off this issue also. https://github.com/ytti/oxidized/issues/2081

### CODE REVIEW

**Comment by martydingo** [comment]
Had some trailing whitespaces, probably added by my code documentation tool.. 

All sorted now.

**Comment by wk** [comment]
Hi there!

This looks great! It could use just a bit more documentation so that users can find it as part of the PR:
* A mention in `CHANGELOG.md` taking credit for the new model
* An addition to `docs/Supported-OS-Types.md` mentioning the relevant model and OS type

**Comment by martydingo** [comment]
@wk Thanks very much, I've added some more documentation in, let me know if there's anything else required.

**Comment by martydingo** [comment]
I'm sure the codecov doesn't apply for this situation?

**Comment by djh00t** [comment]
Hi Guys - any movement on this PR?

**Comment by martydingo** [comment]
@djh00t No, still waiting for someone to come along and accept the PR.

**Comment by mortzu** [comment]
Please fix the conflict

**Comment by martydingo** [comment]
> Please fix the conflict

You want me to fix the conflict created by this PR being outstanding for over 12 months and therefore the changelog is conflicted? 

I fixed this once and this has reoccured, is this going to be merged following this fix?

**Comment by mortzu** [comment]
will merge then

**Comment by martydingo** [comment]
@mortzu The `CHANGELOG` has been updated

**Comment by martydingo** [comment]
`lib/oxidized/model/model.rb:196:25: W: Lint/UnusedBlockArgument: Unused block argument - line. You can omit the argument if you don't care about it.`

Is the error, which this PR does not touch. Please merge or reply with any outstanding actions required before the conflict reoccurs. 

Thanks

**Pull request merged**
