### PR TITLE
Dot's in hostnames are frowned upon, but allowed

### PR DESCRIPTION
**Pull request by funzoneq**
```
AMS01.LI17.RM.SW01(config)# hostname "AMS01.LI17.RM.SW01"
Note: To be compliant with RFC 1123, the hostname must contain only letters,
      numbers and hyphens, and must not start or end with a hyphen.
```

### CODE REVIEW

**Comment by ytti** [comment]
If you keep the - as last in group, then you don't need to escape it.

**Comment by funzoneq** [comment]
fixed @ytti

**Comment by ytti** [comment]
Do you need to escape . in character group? I don't think so.

**Comment by funzoneq** [comment]
@ytti it's now officially a one character pull request 👍

**Comment by ytti** [comment]
With three commits :) does not matter, usually nice to rebase multiple typo-fixes/refactors into single commit for better history. Merging.

**Pull request merged**
