### PR TITLE
Add capability to pipe diffs into post_store hooks

### PR DESCRIPTION
**Pull request by gs-kamnas**
This PR implements the following changes:

* Adds the optional capability to pipe the config diff to standard input of handler scripts/binaries in the exec hook.

* Documentation of changes to the exec hook.

### CODE REVIEW

**Comment by wk** [comment]
@gs-kamnas could you explain in a few words on your use case for this functionality? Is this something you use to e-mail diffs out in the style of rancid as an alternative to the [e-mail hook](https://github.com/ytti/oxidized/blob/master/extra/oxidized-report-git-commits)?

**Comment by gs-kamnas** [comment]
While I cannot discuss the details, the use case is to both generate emails in a manner very similar to the email hook, as well as deliver the diffs to a 3rd party NMS solution.

**Comment by wk** [comment]
@ytti this looks mostly harmless, and potentially offers a building block toward a solution for #409 and maybe #561. What's your take on this?

**Comment by mortzu** [comment]
Please process the checklist and fix the conflict

**Pull request closed without merging**
