### PR TITLE
match more 'uptime' line in 'show version' and delete 'show chassis' 

### PR DESCRIPTION
**Pull request by FlorianDoublet**
In some devices the older "uptime" regexp was not efficient, and I deleted 'show chassis' because there is to much differents temperature lines per devices and I think here it's useless (It's more for monitoring).

### CODE REVIEW

**Comment by ytti** [comment]
I recently had chat with someone about the same issue. Maybe StringScanner would help here?

````
ytti@ytti ~/t/moi42> cat moi.rb
#!/usr/bin/env ruby

require 'strscan'

out = ''
string = ARGF.read
sc = StringScanner.new string

sc.scan_until(/^System Up Time.*/)
out << sc.pre_match.chomp
out << sc.scan_until(/^Temperature/)

temp = sc.scan_until /^Fans/
out << temp.gsub(/^(\s*\d+\s*)\d+(.*)/, '\1XX\2')
out << sc.rest
puts out


ytti@ytti ~/t/moi42> cat output
switch-r1#show system
System Description: Dell Ethernet Switch
System Up Time: 578 days, 15h:45m:16s
System Contact: admin
System Name: switch-r1
System Location: S1
Burned In MAC Address: 0025.642C.451D
System Object ID: 1.3.6.1.4.1.674.10895.3013
System Model ID: PCT6248P
Machine Type: PowerConnect 6248P
Temperature Sensors:

Unit     Temperature (Celsius)    Status
----     ---------------------    ------
 1        28                      OK
 2        27                      OK
 3        28                      OK
 4        27                      OK

Fans:

Unit     Description    Status
----     -----------    ------


 1       Fan 1          OK
 1       Fan 2          OK
 1       Fan 3          OK
 1       Fan 4          OK
 1       Fan 5          OK
 2       Fan 1          OK
 2       Fan 2          OK
 2       Fan 3          OK
 2       Fan 4          OK
 2       Fan 5          OK
 3       Fan 1          OK
 3       Fan 2          OK
 3       Fan 3          OK
 3       Fan 4          OK
 3       Fan 5          OK
 4       Fan 1          OK
 4       Fan 2          OK
 4       Fan 3          OK
 4       Fan 4          OK
 4       Fan 5          OK

Power Supplies:

Unit     Description    Status         Source
----     -----------    -----------    ------


 1       Main           OK             AC
 1       Secondary      OK             DC
 2       Main           OK             AC
 2       Secondary      OK             DC
 3       Main           OK             AC
 3       Secondary      OK             DC
 4       Main           OK             AC
 4       Secondary      OK             DC

switch-r1#⏎                                                                                

ytti@ytti ~/t/moi42> ./moi.rb output 
switch-r1#show system
System Description: Dell Ethernet Switch
System Contact: admin
System Name: switch-r1
System Location: S1
Burned In MAC Address: 0025.642C.451D
System Object ID: 1.3.6.1.4.1.674.10895.3013
System Model ID: PCT6248P
Machine Type: PowerConnect 6248P
Temperature Sensors:

Unit     Temperature (Celsius)    Status
----     ---------------------    ------
 1        XX                      OK
 2        XX                      OK
 3        XX                      OK
 4        XX                      OK

Fans:

Unit     Description    Status
----     -----------    ------


 1       Fan 1          OK
 1       Fan 2          OK
 1       Fan 3          OK
 1       Fan 4          OK
 1       Fan 5          OK
 2       Fan 1          OK
 2       Fan 2          OK
 2       Fan 3          OK
 2       Fan 4          OK
 2       Fan 5          OK
 3       Fan 1          OK
 3       Fan 2          OK
 3       Fan 3          OK
 3       Fan 4          OK
 3       Fan 5          OK
 4       Fan 1          OK
 4       Fan 2          OK
 4       Fan 3          OK
 4       Fan 4          OK
 4       Fan 5          OK

Power Supplies:

Unit     Description    Status         Source
----     -----------    -----------    ------


 1       Main           OK             AC
 1       Secondary      OK             DC
 2       Main           OK             AC
 2       Secondary      OK             DC
 3       Main           OK             AC
 3       Secondary      OK             DC
 4       Main           OK             AC
 4       Secondary      OK             DC

switch-r1#
ytti@ytti ~/t/moi42> 
````

**Comment by FlorianDoublet** [comment]
That's right, it could help. But I don't understand why show chassis is important for a backup program ? Do you really think that it's usefull for oxidized to get it ?

**Comment by ytti** [comment]
Rancid does it, so lot of people are accustomed to it, I'm ambivalent. If you blow up your PSU or fan, you could use configuration backups to traceback when it happened.
Perhaps other model authors @fhibler @dotwaffle @nopedial and also @sid3windr could chime in.

Some people take this even further @RichiH is happy to write some documents on his use-case about collecting dynamic information, like routing-table, BGP/OSPF neighbours etc.

**Comment by sid3windr** [comment]
Yea, that moi.rb chat was with me ;)

It depends on how you look at things; it's not terribly useful for a configuration backup program, but it does track status of power supplies and such, so you could go back in your version control system and see when a secondary PSU was attached or so.

Rancid also mails diffs which I find useful - it can act as a silly secondary monitoring system as it'll mail you a diff saying Temperature is not OK or so.

If you regard it as a simple config backup program, it is indeed not of importance (similar to "why would you remove passwords from your config, it's not a config backup anymore then - rancid has that option).

I don't mind having show chassis in there as long as the temps can be masked out to avoid useless commits :)

**Pull request closed without merging**
