### PR TITLE
Added model Hirschmann HiOS

### PR DESCRIPTION
**Pull request by tijldeneut**
## Pre-Request Checklist
- [x ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [ ] Changes are reflected in the documentation
- [x ] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
Added model Hios for Hirschmann Greyhound HiOS Switches.

### CODE REVIEW

**Comment by mortzu** [comment]
We already have a model: https://raw.githubusercontent.com/ytti/oxidized/master/lib/oxidized/model/hirschmann.rb

**Comment by tijldeneut** [comment]
@mortzu , that is correct, but Hirschmann has two different types of operating systems. 
Older is Mach, which is the one the hirschmann.rb file is written for.
Newer is HiOS, which is what mine is written for
Unfortunately they are not mutual inclusive: e.g. the command for dumping the config on one is `show running-config` and the other is `show running-config script` and they will not function on a different switch. Also the prompt has changed.

In our company we are actually using both hirschmann.rb (older devices) and hios.rb (newer devices).

**Comment by mortzu** [comment]
According to https://github.com/ytti/oxidized/blob/master/docs/Supported-OS-Types.md the hirschmann.rb is for HiOS

**Comment by tijldeneut** [comment]
Ok, let me check; that documentation also needs to be updated and I'll do a new pull request :-)
I'm guessing there is a CLI difference between HiOS 5 and HiOS 6, but I'll get back to you. In any case, both are Hirschmann managed switches and both have a different CLI implementation.
Source: https://hirschmann.com/fr/produits_Hirschmann/Ethernet_industriel/Software/Software_Platforms/HiOS-Hirschmann-Operating-System_HiOS_6.0/index.phtml

**Pull request closed without merging**
