### PR TITLE
capture ZebOS configuration from F5

### PR DESCRIPTION
**Pull request by yzguy**
## Pre-Request Checklist
- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [ ] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
When running an F5, you can configure Advanced Routing, this in generally BGP. This BGP configuration is done through `imish`, which drops you in ZebOS. This configuration is useful to capture/audit for changes as it affects traffic as much as any other configuration

### CODE REVIEW

**Comment by wk** [comment]
Thanks! Pulling this as-is. Can you confirm that the ZebOS configuration file exists on the filesystem even when this functionality is not enabled / configured on the device, and thus users who do not make use of the feature will not be greeted with an unexpected error as a result?

**Comment by yzguy** [comment]
ah yeah, that'll cause an issue. I spun up an AWS one quick and the zebos folder is not there. I'll get a PR up for a better solution.

**Comment by wk** [comment]
Thanks! I'll keep this in for now so that you can commit a fix cleanly on top rather than reverting.

**Comment by yzguy** [comment]
https://github.com/ytti/oxidized/pull/1528

**Pull request merged**
