### PR TITLE
Fix for slackdiff.

### PR DESCRIPTION
**Pull request by Punicaa**
## Pre-Request Checklist

- [ ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [ ] Changes are reflected in the documentation
- [X] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
- Updated slackdiff.rb to use slack_ruby_client instead of slack-api.
- Updated default timeout from 20 to 60. 

Fixes users experiencing the following error:

ERROR -- : Hook slack (#<SlackDiff:0x00005572c9621e20>) failed (#<NameError: uninitialized constant Slack::Client>) for event :post_store #2697

### CODE REVIEW

**Comment by robertcheramy** [comment]
I miss the update of the default timeout in the diff. Can you check that?
Can you also merge master into your branch (or rebase it, as you which), and modify Changelog so that the changes are under the unreleased Version?

**Comment by Punicaa** [comment]
Thanks for the comment. Changes from Master pulled and made changes to Changelog and actually changed the timeout.

**Comment by robertcheramy** [comment]
Something whent terribly wrong here, as many commits where integrated in this PR. Mabe a `git rebase` would bring some clarity in the PR?

**Comment by robertcheramy** [comment]
Why should the default timeout be changed? If you don't like it, you can change it in your configuration.

**Comment by robertcheramy** [comment]
> Something went terribly wrong here, as many commits where integrated in this PR. Mabe a `git rebase` would bring some clarity in the PR?

I've rebased your branch. Be sure to update your branch before submitting more commits. You may need a `git reset --hard.

**Comment by robertcheramy** [comment]
You can change the timeout in your configuration file:
```
timeout: 20
```

I'll revert the timeout change an merge into master.

**Pull request merged**
