### PR TITLE
xos false positive diffs, closes #1411 

### LINKED ISSUE #1411: Extreme xos model: false positive diffs
We have found the following false positive diffs:

first one  on Extreme Alpine3804 model at "show diagnostics" section
``` diff --git a/dist-sw-kgroch17-127-188.ctpt b/dist-sw-kgroch17-127-188.ctpt
index b4ae4c0..f996002 100644
--- a/dist-sw-kgroch17-127-188.ctpt
@@ -53,11 +53,11 @@
 # 
 # CPU system health diag result
 #                   Total Tx   Total Rx   Total miss  Error Pkt
-#  Type 0:     241932     241932            0           0
-#  Type 1:     241932     241932            0           0
-#  Type 2:     241932     241932            0           0
-#  Type 3:     241931     241931            0           0
-#  Type 4:     241931     241931            0           0
 # 
 # Syntax error at token licenses
 # 
```

second one on Summit200-48:

```diff --git a/accs-sw-kosw57-125-106.ctpt b/accs-sw-kosw57-125-106.ctpt
index 9bc9e95..d20ed3d 100644
--- a/accs-sw-kosw57-125-106.ctpt
@@ -48,7 +48,7 @@
 # Timed Upload:     None scheduled
 # Timed Download:   None scheduled
 # 
-# Temperature:      Normal.    All fans are operational.
 # Power supply:     Internal power supply OK
 # 
 # Default Cfg Mode: Standard

diff --git a/accs-sw-kosw57-125-106.ctpt b/accs-sw-kosw57-125-106.ctpt
index 9bc9e95..d20ed3d 100644
+++ b/accs-sw-kosw57-125-106.ctpt
@@ -48,7 +48,7 @@
 # Timed Upload:     None scheduled
 # Timed Download:   None scheduled
 # 
+# Temperature:      Normal as usual.    All fans are operational.
 # Power supply:     Internal power supply OK
 # 
 # Default Cfg Mode: Standard
```

### PR DESCRIPTION
**Pull request by lubiewiatr**
## Pre-Request Checklist

- [ ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [ ] Changes are reflected in the documentation
- [ ] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
Added filtering for temperature from "show switch" output (Summit200-48) and also filtering for interfaces total bandwith from "show diagnostic"(Extreme Alpine3804)

Closes issue #1411

### CODE REVIEW

**Comment by laf** [comment]
@lubiewiatr Can you update the changelog as per the checklist at the top.

**Comment by cchance27** [comment]
Is this going to get merged to release?

**Comment by cchance27** [comment]
Another change to ignore would be  the SysHealth check line

``# SysHealth check:  Enabled (Normal)``

it's not configuration related, and if a switch overheats or has a fan failure it triggers a diff in the configuration backup which is a waste, especially if you are like me and have an annoying switch that misreports an overheat and constantly switches back and forth between Normal and Alerted/Overheat you end up with a lot of useless diff noise.

**Comment by mortzu** [comment]
Can you please fix the conflict?

**Pull request closed without merging**
