### PR TITLE
unspeakable things took place in original PR, correcting model

### PR DESCRIPTION
**Pull request by wk**
Premature PR with faults mistakenly considered tested. Regrets were had. Correcting.

### CODE REVIEW

**Comment by Turbid** [comment]
@wk #1252 my PR. I will now check your version

**Comment by wk** [comment]
@Turbid thanks! This one also moves prompt stripping to all commands (vs. from configuration display only). Looking forward to your findings!

**Comment by Turbid** [comment]
@wk work fine, tnx

**Comment by wk** [comment]
@Turbid thanks for the the new os type and testing!

@ytti please pull this to correct committed PR #1251 that turned out a tad premature. Poignant reminder of a timeless proverb: "Семь раз отмерь, один раз отрежь".

**Pull request merged**
