### PR TITLE
Ssh key support

### PR DESCRIPTION
**Pull request by awlx**
Adds the functionality to provide a ssh public and privatekey to use for SSH GIT connect.

### CODE REVIEW

**Comment by danilopopeye** [comment]
@awlx no tests for this? :cry:

**Comment by awlx** [comment]
Sorry, was a quick fix to get it finally working. Tests will follow when I have time.

**Comment by danilopopeye** [comment]
@awlx I haven't test this, but it should be close :wink:

``` diff
-      it "will push to the remote repository using ssh" do
-        Oxidized.config.hooks.github_repo_hook.remote_repo = 'git@github.com:username/foo.git'
-        Rugged::Credentials::SshKeyFromAgent.expects(:new).with(username: 'git').returns(credentials)
-        gr.cfg = Oxidized.config.hooks.github_repo_hook
-        gr.run_hook(ctx).must_equal true
+      describe "will push to the remote repository using ssh" do
+        before do
+          Oxidized.config.hooks.github_repo_hook.remote_repo = 'git@github.com:username/foo.git'
+          Oxidized.config.hooks.github_repo_hook.pubkey = 'pubkey'
+          Oxidized.config.hooks.github_repo_hook.privkey = 'privkey'
+        end
+
+        it "using credentials" do
+          Rugged::Credentials::SshKeyFromAgent.expects(:new).with(username: 'git').returns(credentials)
+          gr.cfg = Oxidized.config.hooks.github_repo_hook
+          gr.run_hook(ctx).must_equal true
+        end
+
+        it "using public and private keys" do
+          File.expects(:expand_path).with('pubkey').returns('/pubkey')
+          File.expects(:expand_path).with('privkey').returns('/privkey')
+
+          Rugged::Credentials::SshKey.expects(:new).with(username: 'git', publickey: '/pubkey', privatekey: '/privkey').returns(credentials)
+          gr.cfg = Oxidized.config.hooks.github_repo_hook
+          gr.run_hook(ctx).must_equal true
+        end
```

**Comment by danilopopeye** [comment]
@awlx another thing, what do you think of using the same keys that Rugged use: `publickey` and `privatekey` ?

/cc @ytti + @ElvinEfendi

**Comment by awlx** [comment]
Feel free, also thought about it. But I am lazy and thought short config options are better ;).

**Comment by ytti** [comment]
@danilopopeye publickey and privatekey are probably more descriptive yes.

**Comment by awlx** [comment]
Fixed the variable names.

**Comment by danilopopeye** [comment]
@awlx let me know if you have problem with the tests :smiley:

**Comment by awlx** [comment]
@danilopopeye how do I test if they work the way I expect them to ? :D

**Comment by danilopopeye** [comment]
@awlx the other [comment](https://github.com/ytti/oxidized/pull/343#issuecomment-188902394) I've made, already does this.

``` ruby
it "using public and private keys" do
  # this line here
  Rugged::Credentials::SshKey.expects(:new).with(username: 'git', publickey: '/pubkey', privatekey: '/privkey').returns(credentials)
  gr.cfg = Oxidized.config.hooks.github_repo_hook
  gr.run_hook(ctx).must_equal true
end
```

The line I marked, tests the class `Rugged::Credentials::SshKey` must received a call to `#new` with the hash: 
`{ username: 'git', publickey: '/pubkey', privatekey: '/privkey' }`.

Have I made sense?

**Comment by awlx** [comment]
Yeah, that makes sense. My question was more "how do I test the test?".

**Comment by danilopopeye** [comment]
Oh, sorry! Must have needing more :coffee:! That diff is for the `spec/githubhook_spec.rb` file, it should be around line `115`.

**Comment by ElvinEfendi** [comment]
> @awlx another thing, what do you think of using the same keys that Rugged use: publickey and privatekey ?

:+1: I also think we should keep it consistent with Rugged's keys.

**Comment by awlx** [comment]
It's already renamed and merged :). Tests will follow soon. 

THX for the feedback!

**Pull request merged**
