### PR TITLE
add support for hp msa storage

### PR DESCRIPTION
**Pull request by aschaber1**
tested with hp msa 2040 storage system

### CODE REVIEW

**Comment by ytti** [comment]
1. What does the ```telnet``` method do there?
 2. Why is there expect for more prompt, when pager is actually disabled?
 3. Why is telnet in cfg block, while there is no telnet username/password prompt shown?

It is perfectly fine to submit SSH only model. Only submit what you've tested and known to work. To me it seems you can remove telnet from config, telnet model and the expect pager thing.

**Comment by ytti** [comment]
Also please edit README.md accordingly. 

We really prefer if the models are called by the operating system name, so if you can find operating system name, use that. Spend some time researching, we understand often there simply isn't any particular name for the operating system.

**Comment by ytti** [comment]
bump

**Comment by ytti** [comment]
bump

**Comment by laf** [comment]
@aschaber1 Any updates to this?

**Comment by aschaber1** [comment]
hello @ytti, @laf 
just rebased/pushed the cleanup.
I didn't find any other os name, so I'd stick with hpmsa.
regards

**Comment by laf** [comment]
You've got two model files now, hpemsa and hpmsa, can you remove the redundant one?

**Pull request merged**
