### PR TITLE
added support for Ciena SOAS 6.x device type

### PR DESCRIPTION
**Pull request by jgroom33**

### CODE REVIEW

**Comment by ytti** [comment]
Thanks great work!

**Comment by jgroom33** [comment]
Thanks.  What is the process for updating the gem?  (I'm new to ruby)
Should I create a new pull request with a modification to the changelog and gemspec file?

**Comment by ytti** [comment]
We don't update it after every change. If you want build new gem just for you. You can type 'rake build' and gem should appear in gems/ directory, which you can then install with 'gem install XYZ' on same or another machine.

**Comment by jgroom33** [comment]
I finally figured this out.  oxidized-web requires oxidized. so I had to rename the created gem to oxidized I also had to bump the version up in the gemspec file to insure the correct gem was being installed.

Thanks for the guidance

**Pull request merged**
