### PR TITLE
Edit init script

### PR DESCRIPTION
**Pull request by MajesticFalcon**
Making it more obvious to users what needs to happen

### CODE REVIEW

**Comment by ytti** [comment]
From casual view, earlier to me is obvious what are local and what I need to change. The new looks like maybe they magically appear from somewhere.

I don't mind, just odd.  Perhaps we should assume user to be oxidized and assume binary to be in path and require configuration when that is not true?

**Comment by MajesticFalcon** [comment]
That makes more sense. For some reason, my eyes didn't notice 'sts'. I assumed it would have been defaulted to oxidized.

**Comment by ytti** [comment]
I would have just assume oxidized binary is in path and just use 'oxidized'. If it's not in path, have someone change it?

**Comment by MajesticFalcon** [comment]
Yeah, I tried that first. For some reason, I get the following error. 'start-stop daemon unable to stat '//oxidized'' When I run start-stop-daemon manually with -exec oxidized, it does the same thing

**Comment by ytti** [comment]
Maybe $(which oxidized)

**Comment by MajesticFalcon** [comment]
$(which oxidized) starts the server

**Comment by ytti** [comment]
I meant DAEMON=$(which oxidized)

**Comment by MajesticFalcon** [comment]
That worked for me.

**Pull request merged**
