### PR TITLE
Add F5 BIG-IP model

### PR DESCRIPTION
**Pull request by mikebryant**

### CODE REVIEW

**Comment by ytti** [comment]
Is BIG-IP the operating system name?

**Comment by mikebryant** [comment]
This is the output of `tmsh show sys version`
```
Sys::Version
Main Package
  Product     BIG-IP
  Version     11.6.0
  Build       5.123.429
  Edition     Engineering Hotfix HF5
  Date        Tue Aug 11 13:51:32 PDT 2015
```

I'm not entirely sure whether you'd call the operating system `BIG-IP` or `TMOS` - https://support.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/tmos_management_guide_10_1/tmos_intro.html#1023662

What do you think?

**Comment by ytti** [comment]
To me TMOS looks like the OS. Why I think naming things as OS is important, is that often vendors keep using same product name when they introduce new OS.

I'd prefer TMOS if that's ok with you.

**Comment by mikebryant** [comment]
Sure, I don't mind. Updated.

**Comment by ytti** [comment]
Thanks a bunch for this, always great to have new models, especially as common kit as this.

**Comment by mikebryant** [comment]
No problem.

Just working through all the devices we have here, it's nice to be able to give back :)

**Pull request merged**
