### PR TITLE
#1633 fix for NOS timestamps in show version

### PR DESCRIPTION
**Pull request by f0rkz**

### CODE REVIEW

**Comment by f0rkz** [comment]
Bump, anyone get a chance to review this?

**Comment by wk** [comment]
@f0rkz please see comment on the related issue. This looks good, but there may be an opportunity to generalize to catch the uptime line of additional device types covered by this model.

**Comment by f0rkz** [comment]
@wk went ahead and added those two cases. Let me know if we need to add more.

**Comment by wk** [comment]
LGTM, pulling this in.

**Pull request merged**
