### PR TITLE
As for license info

### PR DESCRIPTION
**Pull request by pozar**
## Pre-Request Checklist

- [ ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [ ] Changes are reflected in the documentation
- [ ] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description

In order to track what devices support 10G uplinks, a "show license" has been added.

### CODE REVIEW

**Comment by pozar** [comment]
Just checking in as I have another PR I would like to submit on this file.

**Comment by wk** [comment]
This looks good, but could benefit from an attribution line added to `CHANGELOG.md` documenting the change in short.

**Comment by pozar** [comment]
@wk Not sure where to put that as I don't know what version this would go into.  A suggested CHANGELOG line could look like...

FEATURE: added query for AOS licenses to see what feature set is on the switch and when added (@pozar )

**Comment by wk** [comment]
Thanks! I've updated the changelog on your behalf and pulled this in.

**Pull request merged**
