### PR TITLE
Cisco VPN3000 & NetGear Smart switches support

### PR DESCRIPTION
**Pull request by baznikin**
## Pre-Request Checklist

- [ ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [ ] Changes are reflected in the documentation
- [ ] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

### CODE REVIEW

**Comment by baznikin** [comment]
Sorry, I messed up with branches on my fork! I intended to create two pull requests... So, here we have to models:

1) Cisco VPN 3000 - legacy VPN concentrator. It have buggy ssh v1, but ftp works pretty well

2) NetGear PROSafe Smart switches:

Created for "XS716T ProSAFE 16-Port 10-Gigabit Smart Managed Switch". Not sure what models it fits as well, at least NETGEAR XS708T, XS712Tv2, XS716T, XS728T, XS748T
Those switches doesn't have CLI at all, only web interface.
cmd :secret not tested, blindly copypasted from netgear.rb

**Comment by baznikin** [comment]
@wk done!

**Comment by wk** [comment]
@baznikin thanks! Looks good! Pulling this in.

@ytti I believe the implementation of `netgearxs716.rb` by @baznikin here is the first instance of the `http` input being used by an external contributor on completely independent basis, which is wonderful to see. You might want to take a moment to review if the emerging utilization pattern aligns with your vision for this input.

**Comment by wk** [comment]
It seems I've initially failed to notice this, but for some reason in the original PR, the location of the `netgearxs716.rb` file was in the project root instead of in `/lib/oxidized/model/` for some reason; corrected this in a subsequent pull.

**Comment by baznikin** [comment]
My bad! sorry about it.
I can't tell it is completely independent, I use other models as example.

**Pull request merged**
