### PR TITLE
#1061 Handling devices that only prompt for password via SSH

### PR DESCRIPTION
**Pull request by ja-frog**
For #1061 
An approach to handling devices that do not prompt for a username, only a password when connecting via ssh. The Calix B6 inspired this.

### CODE REVIEW

**Comment by laf** [comment]
You might also need to rebase from master as the travis ci checks are currently failing.

**Comment by laf** [comment]
@wk What do you think to this change?

**Comment by wk** [comment]
This looks like an improvement that should not have any side effects.

In the broader context, it might be desirable to also handle the case where a username prompt has been configured and observed, but resulted in a successful login immediately after the username was sent without being subsequently prompted for a password. It might also make sense to see if standardizing on the same logic both here and in `telnet.rb` is possible.

**Comment by ytti** [comment]
Or maybe rather:

```ruby
    def login
      match_re = [ @node.prompt ]
      match_re << @username if @username
      match_re << @password if @password
      match = expect match_re
      until match == @node.prompt
        cmd(@node.auth[:username], nil) if match == @username
        cmd(@node.auth[:password], nil) if match == @password
        match = expect match_re
      end
    end
```

To honour stated desire in model, so that we don't even try to do passowrd/user if they are not asked in model, to avoid working with broken models.

**Comment by laf** [comment]
@ja-frog Mind adding the above in to this PR and give it a test, I'll do another test once it's ready.

**Comment by ytti** [comment]
Anyone able to test this? I have exactly zero devices which use SSH but authenticate terminal. Pong @ja-frog

**Comment by ja-frog** [comment]
I should be able to try this out tomorrow.

**Comment by ja-frog** [comment]
@ytti @laf  I'm sorry for having such a long turn around. I tested this and it passed with all of our ssh devices. That would be the B6s along with Netonix and Cisco switches and router.

**Pull request merged**
