### PR TITLE
Fix rubocop warnings

### PR DESCRIPTION
**Pull request by robertcheramy**
## Pre-Request Checklist
- [X] Passes rubocop code analysis (try `rubocop --auto-correct`)

## Description
This PR fixes a lot of rubocup warnings.
I did not fix all warnings in .rubocop_todo.yml, as I did not felt safe doing so. It would be a better Idea to fix them when touching this part of the code.
I preferred small commits in order to find out a problem easier if there is one. It tried to test as much as possible.

Closes issue #2983

### CODE REVIEW

**Comment by robertcheramy** [comment]
@ytti and @aschaber1 - if would be great if you would find time to look into this PR.
@aschaber1  - I have changed a member name in refinements.rb (Commit f60ec9381f9120152ffde2a4c96534dcf05f7709)
@ytti - I changed constant names in different commits, commented suppressed exceptions, and so on - that's a lot, and hope this is OK for you.

**Comment by robertcheramy** [comment]
I plan to merge this PR next week (starting 11.12.2023) if there is no reaction from the reviewers until then.

**Comment by aschaber1** [comment]
Havent tested it, but looking at the PR: LGTM

**Comment by ytti** [comment]
I thought I found serious issue, but I think i''m wrong. I don't see problems, but I'm also not confident as I didn't spend much time and won't spend. But at least someone is doing something, and if something breaks, as long as it gets fixed, that's still progress.

**Pull request merged**
