### PR TITLE
Fix issue #1893

### PR DESCRIPTION
**Pull request by raunz**
## Description
Change makes possible to use more specific 'false' values on top of less specific 'true' values.

Closes issue 1893

### CODE REVIEW

**Comment by ytti** [comment]
You are double checking the first condition

**Comment by raunz** [comment]
Indeed. Missed that. I'll correct the code, rerun tests and make a new PR later. Apologies.

**Comment by ytti** [comment]
Perhaps we want to ignore nil values? So that false is used as falsy terminating and nil is used to revert to less specific value? I could imagine use-case, when you can't avoid returning value, but you don't want to actually override less specific?

**Comment by raunz** [comment]
The scenario, when the key exists, but the value is nil, can be achieved with a bad configuration. I assume, that we shouldn't specially check for nil? to catch that corner case.
If the return value of `vars` is used by if conditional, then it doesn't make difference, is it nil or false.

**Comment by ytti** [comment]
It does matter, consumer of variable can test if it's false or nil. So against my initial thought, we must terminate on both, so the code is fine.

**Pull request closed without merging**
