### PR TITLE
[RFC] Create a model for Linksys SRW switches

### LINKED ISSUE #875: question: Linksys SWR support feasible?
Hi, I wanted to add support for our Cisco/Linksys SRW2048, which has a very peculiar CLI:
- telnet/ssh to the switch
- login (curses style menu login - move to password field with TAB)
- press CTRL-z
- input "lcli"
- login again
- input "show startup-config"
- input "exit"
- input "logout"

My question is if it is feasible to do this with oxidized?

### PR DESCRIPTION
**Pull request by glance-**
## Pre-Request Checklist

- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [ ] Changes are reflected in the documentation
- [ ] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
This creates a model for Linksys SRW switches by sneaking out form the
menu mode and starting the lcli tool to be able to dump the config.

Due to the fact that we're navigating and escaping from a curses mode
not using the regular username/password entry procedures,
but rather chaining a bunch of expect to do the login and start the
lcli terminal mode.

This resolves #875

This is a RFC for Linksys SWR support. I'm probably abusing a lot of code here, and I should write both documentation and some explaining about the model but I'm throwing this out there for some early feedback.

### CODE REVIEW

**Comment by wk** [comment]
Clever. Terrible, but clever. At minimum it'll need a `CHANGELOG.md` line documenting the model, a and a `Supported-OS-Types.md` entry as part of this changeset. Perhaps a `Model-Notes` file explaining what's going on would help as well. 

You might want to check if the SRW-series of Linksys switches is the only one that supports this, and if Linksys perhaps has a name for the OS type; naming models after running code rather than products makes it easier to map new variants as they appear.

**Comment by glance-** [comment]
The switches present them self as:
Operating System: Cisco Small Business Software , so that might be a clue one can use to figure out which other models run the same software. I don't know of any other than the Linksys SRW series which have this odd cmdline gui which one can break out of.

I'll write up some documentation and update the patch.

**Comment by MrMarioMichel** [comment]
Hi @glance- !

```
Sadly mine asks after the lcli not only for the username, it also asks for the password once again. 


                               Switch Main Menu
                               ================

                         1. System Configuration Menu

                         2. Port Status

                         3. Port Configuration

                         4. System Mode (Layer 2 / Layer 3)

                         5. Help

                         0. logout





                                                                                
ArrowKey/TAB/BACK=Move  SPACE=Toggle  ENTER=Select  ESC=Back



### Many new lines ###





>22-Jul-2021 12:36:45 %AAA-I-DISCONNECT: User CLI session for user USERNAME over ssh , source 192.168.132.23 destination  0.0.0.0  TERMINATED. The Telnet/SSH session may still be connected.
lcli

User Name:USERNAME 
Password:
```

I tried with this. 

```
  cfg :ssh do
    # Pre-cli-shell just expects a username, who its going to log in.
    username /^User Name:/
    password /^Password:/
    post_login 'terminal datadump'
    pre_logout 'exit'
    pre_logout 'logout'
  end
```
As you can see I added a Password line as well changed the :telnet do to ssh which could be also a additional module but i just chnaged it since we dont use telnet anymore. Sadly the password wasn't pasted in what did I do wrong ?

BTW: Overall the module works great with all the special chars needed to be sent to the switch to get the cli opened. 

BR Mario

**Comment by MrMarioMichel** [comment]
My mistake, wrong Regex. 

````
  cfg :ssh do
    # Pre-cli-shell just expects a username, who its going to log in.
    username /^User Name:/
    password /Password:/
    post_login 'terminal datadump'
    pre_logout 'exit'
    pre_logout 'logout'
  end
````

Now it machetes the prompt and pastes in the password only thing that cloud cause some errors if there are some SWs with and without lcli passwords.

**Comment by glance-** [comment]
Thanks @MrMarioMichel . I've included your suggestion in a new version of this PR.

@wk I've now written some documentation about these switches and this model.

**Comment by mortzu** [comment]
Can you fix the conflict?

**Pull request merged**
