### PR TITLE
Support group unique ssh keys for githubrepo hook

### PR DESCRIPTION
**Pull request by mjbnz**
## Pre-Request Checklist

- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [x] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
This patch adds support for group unique ssh keys for the githubrepo hook.

Keys are specified by private key only (public keys for Rugged are assumed to be the same filename + `.pub`), in the `remote_repo` configuration option. The patch supports existing functionality of:
```
remote_repo:
  group1: <remote_url1>
  group2: <remote_url>
```
and expands to support:
```
remote_repo:
  group1:
    url: <remote_url1>
    privatekey: <priviate_key1>
  group2:
    url: <remote_url>
    privatekey: <priviate_key2>
```

### CODE REVIEW

**Comment by mjbnz** [comment]
This branch is on top of my 'rubocop-fixes' branch, hence the extra commits.

**Comment by mortzu** [comment]
Can you reflect the change in the documentation please?

**Comment by mjbnz** [comment]
> Can you reflect the change in the documentation please?

Done, and fixed a bug I'd introduced (Asetus doesn't support `.dig()`)

**Comment by mortzu** [comment]
Please fix the merge conflict

**Pull request merged**
