### PR TITLE
Added support for setting ssh auth methods

### PR DESCRIPTION
**Pull request by laf**
This reverts https://github.com/ytti/oxidized/pull/128 which will cause a breaking change for Arista EOS devices. However, `keyboard-interactive` shouldn't be in by default as it causes some models (at least `IOS` and `NXOS`) that fail auth to hang on an interactive prompt waiting for a password which never times out.

To compensate for that, in EOS you can change the ssh authentication mode as per the model specific notes or by enabling `keyboard-interactive` in the oxidized config.

I've also included a fix (but am happy to move this to another PR) for when jobs_done incremented past the total number of nodes. For this we now reset the counter back to 0.

### CODE REVIEW

**Comment by laf** [comment]
I've rebased this now to fix the conflict.

**Comment by yeled** [comment]
Is there an issue # for the hanging forever bug?

How about you ship with the feature that doesn’t change for people using `keyboard-interactive` and the people affected by the hanging bug can take advantage of your new setting to remove the login method that stalls.

also is there a # for the `jobs_done` problem?

**Comment by laf** [comment]
@yeled Thanks for taking a look.

The issue for the hanging is #887.

I can definitely change the defaults to include it so it remains the same as is now. However the default originally was not to have it and it was added in to fix one model that was broken so it does seem overall better to revert back to how it was before. I'm not bothered which way we go.

No issue for the job_done issue, I just found it by adding loads of debug output whilst trying to find why Oxidized ground to a halt after a bit. I can split that out if needs be.

**Comment by ytti** [comment]
Needs conflict resolution

**Comment by laf** [comment]
Done and rebased.

I blame @wk for these :D

**Comment by wk** [comment]
@laf laf/oxidized#1

**Comment by laf** [comment]
@wk :)

Thanks for that. I'd actually just pushed: https://github.com/ytti/oxidized/pull/1175/commits/7701ee6ba338348acce08c8fc941244b909842cf

What's the difference out of interest - I'm not a ruby dev :)

**Comment by wk** [comment]
@laf the original laf/oxidized#1 was submitted just before you've had a chance to fix the tests, so the remaining difference was just the syntactic %w :)

This now passes CI and can go in.

**Comment by laf** [comment]
> @laf the original laf/oxidized#1 was submitted just before you've had a chance to fix the tests, so the remaining difference was just the syntactic %w :)
> 
> This now passes CI and can go in.

Thanks @wk. Appreciate the insight :)

**Pull request merged**
