### PR TITLE
Using socket instead of resolv

### PR DESCRIPTION
**Pull request by casdr**
I found there were some problems with local devices and DNS. I replaced Resolv with IPSocket and it worked.

### CODE REVIEW

**Comment by ytti** [comment]
This does not make sense to me.
http://ruby-doc.org/stdlib-1.9.3/libdoc/resolv-replace/rdoc/IPSocket.html

```ruby
               # File resolv-replace.rb, line 8
def getaddress(host)
  begin
    return Resolv.getaddress(host).to_s
  rescue Resolv::ResolvError
    raise SocketError, "Hostname not known: #{host}"
  end
end
```

it should be doing exactly the same thing. Except perhaps with choosing DNS server. 
I'm also uncertain if it now raises different errors or same, here the raised error is used:

```
./oxidized/nodes.rb:          rescue Resolv::ResolvError => err
```


Can you try the old code, but without calling #new? Just Resolv.getaddress?

**Comment by itscassa** [comment]
Can you try the old code, but without calling #new? Just Resolv.getaddress?

Nope, didn't work. I'm having the same issue.

**Comment by ytti** [comment]
What error IPSocket raises when it can't resolve?

**Comment by ytti** [comment]
Bump? What error do you get? What kind of problems? I'm hesitant to make this change until I understand what is broken.
Can you replicate the problem in irb/pry shell?

# irb
require 'resolve'
Resolv.new.getaddress 'google.com'

**Comment by ytti** [comment]
bump

**Comment by supertylerc** [comment]
@casdr, any update?  What are the issues with "local devices"?  What is a local device?  Are you talking about hosts stored in `/etc/hosts`?

**Comment by casdr** [comment]
Seems like this was fixed, see #314

**Pull request closed without merging**
