### PR TITLE
Add JSON source class.

### PR DESCRIPTION
**Pull request by sargon**
With this class we can utilise JSON files directly without the redirection via a HTTP server. This massivly improved our configuration delivery process, because we are able to deliver cached configuration to oxidized without changes on the delivering service, which would have been much more complicated.

## Pre-Request Checklist

- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [x] Tests added or adapted (try `rake test`)
- [x] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
Adds an additional source class which is able to process JSON encoded files, like the HTTP source does.

### CODE REVIEW

**Comment by ytti** [comment]
Do we want to have separate string_navigate methods for HTTP object  and JSON file object? I feel like in absense of having good reason to have duplicate methods, we should only have one method for maintainability and least amount of surprises.

**Comment by ytti** [comment]
You could add it to 'source.rb' as all sources inherit from it, so then it'll be available in any source.

I think it's generic enough, because it has nothing to do technically with JSON, it's more navigating any ruby hash like object.

**Comment by sargon** [comment]
> I think it's generic enough, because it has nothing to do technically with JSON, it's more navigating any ruby hash like object.

There is a section method (CSV.open_file) that is utilized, I guess the same argument can be applied.

**Comment by ytti** [comment]
> > I think it's generic enough, because it has nothing to do technically with JSON, it's more navigating any ruby hash like object.
> 
> There is a section method (CSV.open_file) that is utilized, I guess the same argument can be applied.

i'm not sure I understand that. I mean moving `string_navigate` from http.rb, to source.rb, should make it usable in all sources. 
I'm also not against changing the name of the method, if something more describe pop-ups, like string_navigate_object or whatever.

**Comment by sargon** [comment]
Yes, we are on the same page with the string_navigate method.

The jsonfile source class had a second method duplicated from the csv source class open_file.
Should I proceed with this function in the same way?

**Comment by ytti** [comment]
> Yes, we are on the same page with the string_navigate method.
> 
> The jsonfile source class had a second method duplicated from the csv source class open_file. Should I proceed with this function in the same way?

Yeah, that's fine by me. When moving methods to source.rb, there may be need to reflect little bit, if the method name should remain same or if more clarity is needed on the name. As contextual documentation is removed, the names may become too generic. But I'm ok with or without renaming.

**Comment by ytti** [comment]
Looks good to me.

**Pull request merged**
