### PR TITLE
Added hook for XMPP MUC

### PR DESCRIPTION
**Pull request by mortzu**
We're using XMPP instead of Slack. So I've rewritten the hook for XMPP

### CODE REVIEW

**Comment by danilopopeye** [comment]
@mortzu could you update the `README.md` and `Dockerfile` like the #729 PR ? Other than that, the code seem 👌

**Comment by mortzu** [comment]
Updated README.md and Dockerfile and added some changes we've made in the meantime

**Comment by mortzu** [comment]
Updated again to match new docs refactoring

**Comment by mortzu** [comment]
Please merge it?

**Comment by laf** [comment]
If you can provide a way to test this with a publicly accessible xmpp service then I'll try it out and merge in.

**Comment by mortzu** [comment]
You can register an account at https://www.jabber.org/

**Comment by laf** [comment]
jabber.at got me there :)

**Pull request merged**
