### PR TITLE
datacom.rb: Fix DataCom prompt and pagination issues (#2151)

### PR DESCRIPTION
**Pull request by Zuquim**
## Pre-Request Checklist

- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [ ] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

### prompt issue
Since the release of the new DmOS firmware, right after a successful login, the device displayed a welcome message, such as:
>Password:
>Welcome to the DmOS CLI
><username> connected from <ip_address> using ssh on hostname
>hostname# 

For this reason, the default RegEx was not able to match the prompt.
It was fixed by adding a custom prompt for the DataCom model, with `[\n]?` in the beginning.

### pagination issue
It seams that the `expect(regex)` method that was supposed to workaround pagination was not working as it should. Several RegEx combinations were tried without success. Oxidized routine for these devices timed out every time a command that triggered pagination was executed.

In order to address this issue, considering the old and new firmware versions, the device terminal pagination setting is now being temporarily disabled during the backup routine.

----

Closes issue #2151

### CODE REVIEW

**Comment by wk** [comment]
Hi there!

It has been the general policy of Oxidized to be able to successfully operate in "read only" mode, i.e., as an unprivileged user with no rights to make any modifications (temporary or permanent) to the configuration.

While I see the utility of the approach taken here, I suspect this breaks this promise as a change is introduced (even if promptly reverted). Are there no alternatives available for this model to overcome pagination, such as emulating key presses and stripping the prompts away, or utilizing some runtime / session command to modify this behavior?

**Comment by Zuquim** [comment]
Hey, @wk !

Thanks for the feedback and explanation.

On the following weeks I'll be running some tests on a couple of Datacom device models. When I find a solution that meets the Oxidized policy, I'll commit the updated fix to this branch.

**Comment by diegocanton** [comment]
Thanks...
It's Work in DM4370

**Comment by mortzu** [comment]
Can you fix the conflict

**Pull request closed without merging**
