### PR TITLE
u/panzerfly's patch for 'Cisco ASA - Added support for multiple contexts' with fixes

### PR DESCRIPTION
**Pull request by marnovdm**
work in progress - please do not merge yet, still testing with new 0.20.0 release

### CODE REVIEW

**Comment by marnovdm** [comment]
I think this could be merged for the next release.

**Comment by lance0** [comment]
Woah nice work.

**Comment by panzerfly** [comment]
thank you guys

**Comment by beschen** [comment]
Replaced 0.20.0 asa.rb file with this one and then oxidized crashes when I start the service. What do I need to do to add this our system?

**Comment by marnovdm** [comment]
Hmm odd.. I will test again tomorrow and report back. Thanks for letting me know.

**Comment by marnovdm** [comment]
I somehow managed to mess up the committed code, I'm not a developer so I guess I made some GIT mistake. I added the missing 'end' statement and it should work now, sorry and thanks for pointing it out!

**Comment by bartdebruijn** [comment]
Any idea when this will be included in the release?

**Pull request merged**
