### PR TITLE
Add support for frr in new versions of cumulus

### PR DESCRIPTION
**Pull request by User4574**
This fixes the issue I raised, #1087.

### CODE REVIEW

**Comment by laf** [comment]
Actually just looking at this again, do you need to set the default to quagga so it doesn't break old installs on update? @User4574

**Comment by ytti** [comment]
I think we should set the variable if vars does not, to be backward compatible.

**Comment by bobthebutcher** [comment]
Hello Team,

If @User4574 is unable to address the comments would you consider someone else taking over this PR ? I would be happy to take over with a bit of guidance. I am pretty new to ruby but with some guidance I think I can handle this one. 

Its usefully for my $job so I am keen to get this one across the line.

Cheers,

Brad

**Comment by wk** [comment]
@bobthebutcher based on what I can see, there are three elements here that could use attention:

* Re-base commit on current version of `cumulus.rb` (from what I can see, only cosmetic changes)
* Look into giving `routing_daemon` a sensible default value and pay attention to capitalization of default(s) and FRR names (so that devices with no frr still work as they do today).
* Documentation (perhaps by adding a file to `/docs/Model-Notes`) and `CHANGELOG.md` update.

Together with a bit of testing, it would be a welcome enhancement.

**Comment by wk** [comment]
Closed by #1375

**Pull request closed without merging**
