### PR TITLE
add https proxy info in slackdiff and ciscosparkdiff hook docs

### PR DESCRIPTION
**Pull request by hslabbert**
## Pre-Request Checklist

- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [x] Changes are reflected in the documentation
- [ ] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

### rubocop output

`rubocop` output resulted in a set of changes, but not to any files I had touched.  This is purely a documentation update.  I left the rubocop auto-correct changes out of this commit/PR as I don't want ot mess with anything currently in flight but outside the scope of this PR.

rubocop output:

```
Offenses:

extra/syslog.rb:51:35: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of a hash.
      /(.*)\.ip\.fi/       => '\1',
                                  ^
extra/syslog.rb:57:48: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of a hash.
      :nxos  => /%VSHD-5-VSHD_SYSLOG_CONFIG_I:/,
                                               ^
lib/oxidized/node/stats.rb:13:30: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of a hash.
          :time   => job.time,
                             ^
lib/oxidized/config.rb:53:29: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of a hash.
        'juniper' => 'junos',
                            ^
lib/oxidized/node.rb:102:35: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of a hash.
        :mtime     => @stats.mtime,
                                  ^
lib/oxidized/node.rb:110:32: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of a hash.
          :time   => @last.time,
                               ^
lib/oxidized/node.rb:148:52: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of a hash.
        password:       resolve_key(:password, opt),
                                                   ^
lib/oxidized/input/ssh.rb:9:29: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of an array.
        Net::SSH::Disconnect,
                            ^
lib/oxidized/input/ssh.rb:13:39: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of an array.
        Net::SSH::AuthenticationFailed,
                                      ^
lib/oxidized/input/ssh.rb:14:8: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of a hash.
      ],
       ^
lib/oxidized/input/ftp.rb:14:8: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of a hash.
      ],
       ^
lib/oxidized/input/input.rb:8:28: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of an array.
        Errno::ECONNREFUSED,
                           ^
lib/oxidized/input/input.rb:18:25: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of an array.
        Errno::ETIMEDOUT,
                        ^
lib/oxidized/input/input.rb:19:8: C: [Corrected] Style/TrailingCommaInLiteral: Avoid comma after the last item of a hash.
      ],
       ^

162 files inspected, 14 offenses detected, 14 offenses corrected
```

### rake tests

No new code, but confirmed rake tests passed:

```
Finished in 5.122694s, 6.6371 runs/s, 24.7916 assertions/s.

34 runs, 127 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for RSpec to /home/hslabbert/repos/oxidized-hs/coverage. 932 / 1497 LOC (62.26%) covered.
```

### documentation

This is a documentation update, so it touches only documentation and is necessarily reflected in documentation.

### user visible changes added to [CHANGELOG.md](/CHANGELOG.md)

Didn't touch [CHANGELOG.md](/CHANGELOG.md) as this isn't adding functionality, just adding documentation for existing functionality.

## Description

This just adds references and examples for the `proxy` option under the existing slackdiff and ciscosparkdiff documentation.  I needed to leverage that for slackdiff; got it from the actual slackdiff hook code and validated it works, so adding it to docs for discoverability.

### CODE REVIEW

**Comment by wk** [comment]
There is indeed support for a proxy [here](https://github.com/ytti/oxidized/blob/master/lib/oxidized/hook/ciscosparkdiff.rb#L20) and [here](https://github.com/ytti/oxidized/blob/master/lib/oxidized/hook/slackdiff.rb#L19) which seems to have been left completely undocumented. Thanks for this!

The `rubocop`warnings are likely the result of you having a different version of `rubocop` installed locally than the included `.rubocop_todo.yml` has been generated by, resulting in different rule defaults coming into play which haven't been quashed by configuration.

Is there a reason why you refer in the explanation to the proxy as an `HTTPS Proxy`, but use a `http://` URL in the example? Is this an intentional discrepancy?

**Comment by hslabbert** [comment]
> Is there a reason why you refer in the explanation to the proxy as an HTTPS Proxy, but use a http:// URL in the example? Is this an intentional discrepancy?

Ah, this was largely as I figured the Slack and Spark API endpoints would be HTTPS.  I'm falling back to e.g. Linux env terminology here, e.g.:

http_proxy=http://myproxy:port
https_proxy=http://myproxy:port

...so where both would be using a regular HTTP protocol proxy, but http_proxy is for HTTP resources and https_proxy is for HTTPS resources.

Noted, though, that the terminology there could confusing.  I guess this could just be `s/HTTP\ proxy/proxy/s` and would be simpler and possibly have less risk of confusion?

**Comment by hslabbert** [comment]
Or maybe "a web proxy"?

**Comment by wk** [comment]
If this isn't a reference to any specific capability expected from the proxy server itself, a simple `proxy` seems like the way forward; the example yaml provides sufficient context for a user to understand what is expected.

**Comment by wk** [comment]
Thanks for getting this in!

**Comment by hslabbert** [comment]
perfect; ty

**Pull request merged**
