### PR TITLE
Added Quanta OS

### PR DESCRIPTION
**Pull request by f0o**
Added model for Quanta Switches.

Tested on LB4M switches.

This is my first attempt, perhaps not the best one. Feedback appreciated.

FYI: I had to strip out the comments and the prompt from the `show run` output, I'm uncertain if I did it the right way however it does work.

### CODE REVIEW

**Comment by ytti** [comment]
I would have written ```show run``` differently, but there is no right or wrong answer, it's just personal opinion and I'm not going to enforce any opinion on models. Who ever produces the model, has full say on it.

Could you also include updated README.md in the pull request?

**Comment by f0o** [comment]
Sure thing!

Out of interest, what would the `better` way be to write the `show run` part?



On 13 June 2016 12:17:34 CEST, ytti <notifications@github.com> wrote:
>I would have written ```show run``` differently, but there is no right
>or wrong answer, it's just personal opinion and I'm not going to
>enforce any opinion on models. Who ever produces the model, has full
>say on it.
>
>Could you also include updated README.md in the pull request?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ytti/oxidized/pull/469#issuecomment-225542453

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ytti** [comment]
Purely opinion based. If I had done it right now, I'd probably do one of these:

```
cmd 'show run' do |cfg|
  cfg.each_line.select do |line|
    not line.match /xya/ and
    not line.match /foo/ and
    not line.match /bar/
  end.join
end

cmd 'show run' do |lines|
  cfg = ''
  lines.each_line do |line|
    next if line.match /xya/
    next if line.match /foo/
    next if line.match /bar/
    cfg << line
  end
  cfg
end
```

If I'd do it month from now, I'd probably do something else.

**Comment by f0o** [comment]
@ytti How's it now?

**Comment by ytti** [comment]
If you've tested it, and you're happy with it, I'm happy to merge

**Comment by ytti** [comment]
actually could you change the model name to QuantaOS, more in line with JunOS, IOS, EOS etc?

**Comment by f0o** [comment]
Sure

**Comment by f0o** [comment]
Fixed to QuantaOS resp. `quantaos.rb`

**Comment by f0o** [comment]
deleted the device on my end and readded it, config shows up as expected.
Tested on LB4M

**Comment by ytti** [comment]
Thanks!

**Pull request merged**
