### PR TITLE
Ciscosmb: remove 'sh system' output

### PR DESCRIPTION
**Pull request by Exordian**
## Pre-Request Checklist

- [ ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [ ] Changes are reflected in the documentation
- [X] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
'show system' on a Cisco SG500 emits the following output:
```
System Description:                       SG500-52P 52-Port Gigabit PoE Stackable Managed Switch
System Up Time (days,hour:min:sec):       102,20:25:15
System Contact:                           X
System Name:                              X
System Location:                          X
System MAC Address:                       XX:XX:XX:XX:XX:XX
System Object ID:                         1.3.6.1.4.1.9.6.1.81.52.2

Fans Status:                              OK


          Unit            Temperature (Celsius)            Status          
------------------------ ------------------------ ------------------------ 
           1                        32                       OK            
```

None of these informations are relevant for a backup system IMO. The ever-changing temperature triggers unneeded 'config' changes on oxidized.

### CODE REVIEW

**Comment by davama** [comment]
Could similar argument (monkey wrench) be made here about need for `show system` and other cmds?

**Comment by Exordian** [comment]
> Could similar argument (monkey wrench) be made here about need for `show system` and other cmds?

I agree. I removed the whole command. Location, contact and so can be found in the config as well. I don't think the model type and mac address is needed in oxidized.

**Comment by wk** [comment]
As this is causing a lot of users considerable issues (#1785, #1398, #1500) - and as the output is highly variable across different models and configurations (stacked / unstacked) and fairly complex, removing `show system` and `show bootvar` seems to be the way forward here.

@phurrelmann, I notice you've thumbed down this PR - do you have an alternative approach or any specific concerns?

@Exordian, @davama - do we have consensus on this being the way forward for this model?

**Comment by wk** [comment]
On a deeper review, it seems #1500 had only a single affected user which found a workaround, so `show bootvar` can stay for now.

**Comment by davama** [comment]
I agree 👍

**Comment by menvol3** [comment]
Hi

Could you please add to the following file support for enable command, like in ios.rb

**Comment by davama** [comment]
That is outside this PR.
You could create one with those specifications, it’s not that challenging.
Give it a try, ppl here will let you know if all is well 👍

**Pull request merged**
