### PR TITLE
refactoring, test coverage and github hook

### PR DESCRIPTION
**Pull request by ElvinEfendi**
This PR introduce lots of refactoring specifically related to config and log handling to make testing easier. I've also added `minitest` and `mocha` as testing framework and wrote some more specs. Finally I've added `github` hook that automatically pushes local changes to the repository if configured.

### CODE REVIEW

**Comment by ytti** [comment]
Wow. This looks impressive. I've had glass to many wine to review now, but almost certainly will integrate  tomorrow.

**Comment by ytti** [comment]
Is the rakefile broken? How do I build and push to rubygems with it?

Other than that, I'm ready to merge. Can you solve the conflicts?

**Comment by ElvinEfendi** [comment]
@ytti `Rakefile` was indeed missing the necessary tasks for gem management. I added them back, should be fine now.

Also fixed the conflict.

**Comment by ytti** [comment]
Thanks!

**Comment by ElvinEfendi** [comment]
@ytti when are you planning to push the latest changes in the master to `rubygems`?

**Comment by ytti** [comment]
I'll try to release tomorrow.

**Comment by ElvinEfendi** [comment]
Thanks!

**Pull request merged**
