### PR TITLE
Cluster uptime spam information

### PR DESCRIPTION
**Pull request by brunobritocarvalho**
Everyhour, a new message about the "Cluster uptime". I believe this was added in 5.6 version of Forti.

### CODE REVIEW

**Comment by jsynack** [comment]
This is added to :secret which is only called when `remove_secret: true` is set. 

Should probably be in more generic spot for the model? 

Using this example - I may want to backup my secrets (that is `remove_secret: false`) but I still don't want the repo/config churn because of an uptime stamp that is being incremented.

💭 This also probably brings up a need/desire to have a new method generically for models - that there should be a `:reduce_churn` (or whatever name works) - removing operational counters/things that is outside of the scope of `:secret` (which has other implications). 

This would also give a place to do all the 'normal' gsub fixups such as that.

 But I may be overthinking it. I can see it being useful to have the gsubs right under the device command that was just executed for ease of troubleshooting during model misbehavior versus having to hunt for them in a larger `model.rb`.

**Comment by laf** [comment]
Well spotted. @brunobritocarvalho can you move this so you don't need to enable secrets for it to work please.

**Comment by brunobritocarvalho** [comment]
Point taken, I agreee. Kinda wanted to do that at first but guess I got lazy along the way. 
This should do the trick I believe. Thanks for the input.

**Comment by laf** [comment]
I was just more referring to moving the new line outside of the config check.

I'm not personally (not the projects position) sure that adding another config option to remove what you'd expect to happen by default is the way forward and we should strip out the bad data like this for all.

**Comment by brunobritocarvalho** [comment]
Hmm yeah, also makes sense. I just figured some people would like to have that information and some other would not. I'll make that change tomorrow then.

**Comment by ytti** [comment]
I'm on the fence about reduce_churn. Isn't the expectation that dynamic data, like uptime is not included? Why would @brunobritocarvalho request be unique? 

If it's not unique, we'd need to change all models to output dynamic data, unless variable is set?

**Comment by laf** [comment]
I'd vote not to put a config option in for this and just remove this type of config churn.

**Comment by jsynack** [comment]
Sorry - I wasnt as clear as I could have been.

 My thought process for those comments was to break out the `gsub` and dynamic data removal/reductions in a different method within the model file - but not have it be controlled by a configuration setting / additional variable.  Just have it grouped for easier understanding of what happens in each method.  Sort of a 'this method pulls the config', 'this method scrubs the config' thought process. I am not tied to it at all. 

There is/should be an expectation that a model will behave itself 'out of the box' - and that each poll interval does not cause churn.

**Comment by wk** [comment]
This has been closed by #1047 which introduced unconditional uptime filtering for the `fortios.rb` model.

**Pull request closed without merging**
