### PR TITLE
Remove constantly updating dates from Adtran config

### PR DESCRIPTION
**Pull request by davesbell**
## Pre-Request Checklist

- [ ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [ ] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
Remove constantly updating dates from backup of Adtran config

### CODE REVIEW

**Comment by mortzu** [comment]
please update CHANGELOG.md

**Comment by mortzu** [comment]
Please fix the conflict

**Comment by davesbell** [comment]
Conflict resolved.

**Comment by mortzu** [comment]
Please fix the conflict (again...)

**Comment by davesbell** [comment]
Conflict resolved.

**Pull request merged**
