### PR TITLE
Add supermicro support tested on a SuperMicro SSE-G2252

### PR DESCRIPTION
**Pull request by funzoneq**
Resulting config:

```
Building running configuration. Please wait...
!<stackingDB>00</stackingDB>
!<stackingMac>01_00-25-90-40-c9-a0_02</stackingMac>
!

!

!
!---<InitPhaseConfig>
!---</InitPhaseConfig>
!
!
!
!
prompt sw02.lw.phx
hostname sw02.lw.phx
!
!
!
!
!
!
!
                                                                     !
!
snmp-server community <hidden> rw
snmp-server community <hidden> rw
!
snmp-server enable traps authentication
!
!
username ADMIN access-level 15
username ADMIN <secret removed>
username admin access-level 0
username admin <secret removed>
username lswadmin access-level 15
username lswadmin <secret removed>
enable <secret removed>
!
!
!
!
!
!
!
!
!
vlan database
 VLAN 1 name DefaultVlan media ethernet
 vlan 999 media ethernet
!
!
!
!
!
!
spanning-tree mst configuration
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
interface ethernet 1/1
!
interface ethernet 1/2
!
interface ethernet 1/3
!
interface ethernet 1/4
!
interface ethernet 1/5
!
interface ethernet 1/6
!
interface ethernet 1/7
!
interface ethernet 1/8
!
interface ethernet 1/9
!
interface ethernet 1/10
!
interface ethernet 1/11
!
interface ethernet 1/12
!
interface ethernet 1/13
!
interface ethernet 1/14
!
interface ethernet 1/15
!
interface ethernet 1/16
!
interface ethernet 1/17
!
interface ethernet 1/18
!
interface ethernet 1/19
!
interface ethernet 1/20
!
interface ethernet 1/21
!
interface ethernet 1/22
!
interface ethernet 1/23
!
interface ethernet 1/24
!
interface ethernet 1/25
!
interface ethernet 1/26
!
interface ethernet 1/27
!
interface ethernet 1/28
!
interface ethernet 1/29
!
interface ethernet 1/30
!
interface ethernet 1/31
!
interface ethernet 1/32
!
interface ethernet 1/33
!
interface ethernet 1/34
!
interface ethernet 1/35
!
interface ethernet 1/36
!
interface ethernet 1/37
!
interface ethernet 1/38
!
interface ethernet 1/39
!
interface ethernet 1/40
!
interface ethernet 1/41
!
interface ethernet 1/42
!
interface ethernet 1/43
!
interface ethernet 1/44
!
interface ethernet 1/45
!
interface ethernet 1/46
!
interface ethernet 1/47
!
interface ethernet 1/48
 switchport mode trunk
 switchport allowed vlan add 1,999 tagged
!
interface ethernet 1/49
 no switchport broadcast
!
interface ethernet 1/50
 no switchport broadcast
!
interface ethernet 1/51
 no switchport broadcast
!
interface ethernet 1/52
 no switchport broadcast
!
!
!
!
!
interface vlan 1
 ip address 192.168.100.102 255.255.255.0
!
interface vlan 999
 ip address 12.12.12.12 255.255.255.240
!
!
!
!
!
!
!
!
!
!
!
!
!
ip default-gateway 12.12.12.1
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
ip ssh server
ip ssh server-key size 512
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
interface vlan 1
!
interface vlan 999
!
!
!
!
!
!
!
!
line console
 login
 <secret removed>
 authorization exec default
!
!
line vty
 login
 <secret removed>
 authorization exec default
!
!
!
end
!
! Pool capability code:
!   AM - MAC ACL, A4 - IPv4 ACL, A6S - IPv6 Standard ACL,
!   A6E - IPv6 extended ACL, DM - MAC diffServ, D4 - IPv4 diffServ,
!   D6S - IPv6 standard diffServ, D6E - IPv6 extended diffServ,
!   W - Web authentication, I - IP source guard, I6 - IPv6 source guard,
!   C - CPU interface, R - Rate limit, L - Link local,
!   Reserved - Reserved, ALL - All supported function,
! 
! Unit Device Pool Total Used  Free  Capability                              
! ---- ------ ---- ----- ----- ----- ---------------------------------------- 
!    1      0    0   372    56   316 ALL                                     
!    1      1    0   372    56   316 ALL                                     
!                                                                            
!  Status Bytes      %
!  ------ ---------- ---
!  Free      7458816   5
!  Used    126758912  95
!  Total   134217728
! 
!  Alarm Configuration
!   Rising Threshold         : 95%
!   Falling Threshold        : 90%
! 
! Unit 1
!  Serial Number          : SSG522N02800289
!  Hardware Version       : R02
!  EPLD Version           : 1.00
!  Number of Ports        : 52
!  Main Power Status      : Up
!  Role                   : Master
!  Loader Version         : 1.0.1.2
!  Linux Kernel Version   : 2.6.22.18
!  Boot ROM Version       : 0.0.0.1
!  Operation Code Version : 2.0.0.5
! 
! 
! Software Watchdog Information
!  Status :    Disabled
!  AutoReload :    Disabled
```

### CODE REVIEW

**Comment by ytti** [comment]
Thanks!

There is no better name for the OS than SuperMicro?
Can you also add the device in README.md

I think you may want to remove the top most line 'Building running configuration. Please wait...'?

**Comment by funzoneq** [comment]
@ytti No references to what OS it's running. The only other reference I can find in documentation is 'Super_Switch', but that says even less I guess.

**Comment by ytti** [comment]
There is no way to disable pager in Supermicro?

**Comment by funzoneq** [comment]
@ytti I found the 'disable pager' command :+1:

**Comment by ytti** [comment]
Many thanks!

**Pull request merged**
