### PR TITLE
Added model for Cisco Wireless Lan Controller

### PR DESCRIPTION
**Pull request by casdr**

### CODE REVIEW

**Comment by ytti** [comment]
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/aireos.rb

Is this different? Does Cisco have two WLAN controllers? What are the operating system names?

**Comment by itscassa** [comment]
Hmm, seems like the aireos.rb model works too, but ciscowlc.rb gives the full configuration + statistics. I think the name is AireOS too.

**Comment by ytti** [comment]
​Could you merge them? So that we don't need two models?​

On 11 August 2015 at 12:14, Cas de Reuver <notifications@github.com> wrote:

> Hmm, seems like the aireos.rb model works too, but ciscowlc.rb gives the
> full configuration + statistics. I think the name is AireOS too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ytti/oxidized/pull/159#issuecomment-129784909>.
>



-- 
  ++ytti

**Comment by itscassa** [comment]
Will check that later :-)

**Comment by ytti** [comment]
bump, is this still relevant? Can you merge them?

**Comment by ytti** [comment]
bump.

Any chance you can merge the models?

**Comment by casdr** [comment]
Sorry, the model that's already included works fine :-)

- Cas de Reuver

Website: http://0fi.net
LinkedIn: https://nl.linkedin.com/in/casdr
Twitter: https://twitter.com/cdr_t
Facebook: https://fb.com/casdereuver
GitHub: http://github.com/casdr
Phone: +31632140979

**Comment by ytti** [comment]
Thanks, closing.

**Pull request closed without merging**
