### PR TITLE
Create snr.rb

### PR DESCRIPTION
**Pull request by Turbid**
A simple module for processing the SNR-switchs: https://shop.nag.ru/catalog/04963.SNR

### CODE REVIEW

**Comment by laf** [comment]
Thanks for the PR @Turbid.

What OS do these devices run? I.e Cisco Catalyst run IOS.

Also, can you please update the https://github.com/ytti/oxidized/blob/master/docs/Supported-OS-Types.md doc with this new Vendor / Model.

**Comment by Turbid** [comment]
> What OS do these devices run? I.e Cisco Catalyst run IOS.

The files have the nos prefix, but this is not the OS that is in https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/nos.rb

SNR-S2990G-24(48)T(TX)(FX)(-POE)_7.0.3.5(R0102.0261)_nos.img
SNR-S212i-8POE_5.1.1.420_nos.img

I'm at a loss to say what is this OS

**Comment by laf** [comment]
Ok let's go for snr for now then. Just needs the docs updating with the OS info as per my original response. We can't merge without that.

**Comment by ytti** [comment]
Without ```:all```stripping the prompt etc, likely just using ```cmd "running-config"```wont do it. I feel like down the line 'SNR' might be hard to relate to actual hardware. So maybe at least some comment about what these boxes are in the model? Mayba URL to manufacturer  webpage?

**Comment by wk** [comment]
@ytti @laf @Turbid 

SNR runs IP Infusion's [ZebOS](https://www.ipinfusion.com/products/zebos/) (the internal name of which, confusingly, is `nos`). Thus the correct name for this model would probably be `zebos.rb`. 

Other vendors that make use of this operating system type include some devices from [Planet](http://www.planet.com.tw) and [QTech](http://www.qtech.ru/), among many others.

**Comment by wk** [comment]
@Turbid Could you give a try to [this branch](https://github.com/wk/oxidized/compare/snr-support-refactor) (you only need `lib/oxidized/model/dcnos.rb` from that branch, and can drop it in you `~/.config/oxidized/model/` directory) with the model `dcnos` on your SNR equipment, and see if that works out? 

This is a slightly expanded variant of the model you've contributed.

**Comment by Turbid** [comment]
@wk I will definitely check - next week I will have access to switchs.

**Comment by wk** [comment]
@Turbid have you had a chance to review this yet, and could comment if the [branch](https://github.com/wk/oxidized/compare/snr-support-refactor) works on your devices? This should be turned into a PR, but there don't appear to be any other users for this equipment currently that could validate it.

**Comment by Turbid** [comment]
@wk Thank you - I checked the branch, everything is fine except that you need to remove uptime
image

**Comment by wk** [comment]
@Turbid Thanks! Last push should [correct this](https://github.com/ytti/oxidized/compare/master...wk:snr-support-refactor#diff-ff2ea6360ec4c300cb6952bdcbb069bcR12), could you confirm if that works as expected?

**Comment by Turbid** [comment]
@wk I just fixed it like:
`cfg.gsub! /Uptime is.*/, '' # Omit constantly changing uptime info`

**Comment by wk** [comment]
@Turbid That *should* be equivalent to the one in the upstream branch. If you're OK with this [as-is](https://github.com/wk/oxidized/compare/snr-support-refactor), I'll create a PR so this finds its way into master.

**Comment by Turbid** [comment]
@wk I check again, you version not working:
`2018-04-05 12:52:19 UTC
undefined method `each_line' for nil:NilClass [NoMethodError]
--------------------------------------------------
/var/lib/gems/2.1.0/gems/oxidized-0.21.0/lib/oxidized/model/model.rb:151:in `comment'
/var/lib/gems/2.1.0/gems/oxidized-0.21.0/lib/oxidized/model/dcnos.rb:14:in `block in <class:DCNOS>'
/var/lib/gems/2.1.0/gems/oxidized-0.21.0/lib/oxidized/model/model.rb:94:in `instance_exec'
/var/lib/gems/2.1.0/gems/oxidized-0.21.0/lib/oxidized/model/model.rb:94:in `cmd'
/var/lib/gems/2.1.0/gems/oxidized-0.21.0/lib/oxidized/model/model.rb:136:in `block in get'
/var/lib/gems/2.1.0/gems/oxidized-0.21.0/lib/oxidized/model/model.rb:135:in `each'
/var/lib/gems/2.1.0/gems/oxidized-0.21.0/lib/oxidized/model/model.rb:135:in `get'
/var/lib/gems/2.1.0/gems/oxidized-0.21.0/lib/oxidized/input/cli.rb:14:in `get'
/var/lib/gems/2.1.0/gems/oxidized-0.21.0/lib/oxidized/node.rb:65:in `run_input'
/var/lib/gems/2.1.0/gems/oxidized-0.21.0/lib/oxidized/node.rb:42:in `block in run'
/var/lib/gems/2.1.0/gems/oxidized-0.21.0/lib/oxidized/node.rb:37:in `each'
/var/lib/gems/2.1.0/gems/oxidized-0.21.0/lib/oxidized/node.rb:37:in `run'
/var/lib/gems/2.1.0/gems/oxidized-0.21.0/lib/oxidized/job.rb:9:in `block in initialize'`

**Pull request merged**
