### PR TITLE
Add some OS-Model mapping in README

### PR DESCRIPTION
**Pull request by MajesticFalcon**
I added some of the obvious models. #559

### CODE REVIEW

**Comment by ytti** [comment]
many thanks!

**Comment by danilopopeye** [comment]
@MajesticFalcon why the model `alvarion` was removed in this PR?

**Comment by MajesticFalcon** [comment]
I'm still learning how to use git properly. I must have deleted it on accident.

On Sep 23, 2016, at 11:18 AM, Danilo Sousa <notifications@github.com<mailto:notifications@github.com>> wrote:


@MajesticFalcon<https://github.com/MajesticFalcon> why the model alvarion was removed in this PR?

-

**Comment by ytti** [comment]
ooops, I should've caught that.

**Pull request merged**
