### PR TITLE
add feature about versions and diffs for oxidized-web

### PR DESCRIPTION
**Pull request by FlorianDoublet**
this pull request is for this pull request in oxidized-web : https://github.com/ytti/oxidized-web/pull/11

### CODE REVIEW

**Comment by ytti** [comment]
It looks interesting, but I'm not sure if this is the direction we want to take. 

Also the commit it not against the latest github version, if you look at the git.rb it's the 'single_repo' configuration option (it decides if groups are separate repos or directories in repo).

**Comment by FlorianDoublet** [comment]
updated.

**Comment by laf** [comment]
Is this something that is being considered for merging? It would be handy to have diff support within oxidized-web.

**Comment by ytti** [comment]
I worry about the complexity added in nodes.rb and git.rb, while I also view that most people would do this in their usual git frontend.
But perhaps lot of people actually dont have gitlab, github, stash and no wish to install.

So it feels like I may be alone in my opposition. If so, I am perfectly ok that it is integrated. @nopedial can do it, when he has time to look into it.

Id like to refactor it maybe a bit, but as I wont have time for it any time soon, Im not gonna block integration as-is.

**Comment by laf** [comment]
Understand the concerns :)

I'd certainly vote to include this but happy either way, just don't want to spend time setting something up if this was to be merged in :)

**Comment by SaaldjorMike** [comment]
Would certainly be a nice feature :+1:

**Comment by Rosiak** [comment]
Would really like this too! :+1:

**Comment by anden4380** [comment]
:+1:

**Comment by darkounet** [comment]
:+1:

**Pull request merged**
