### PR TITLE
Extended mysql source (TLS support) 

### PR DESCRIPTION
**Pull request by glaubway**
## Pre-Request Checklist

- [ ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [x] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
Extended mysql source configuration to include TLS options

Close the issue #2096

### CODE REVIEW

**Comment by ytti** [comment]
I would make this drier. You are repeating yourself. Instead you could make an hash then add SSL keys to the hash if SSL is defined and then call the constructor with the hash.

**Comment by glaubway** [comment]
Sorry, but I don't know ruby (have experience with another languages), so I just made it as I understand this and can say that this solution is working in my environment.

**Comment by glaubway** [comment]
I made it a bit clean.

**Comment by mortzu** [comment]
Please fix the merge conflicts

**Pull request merged**
