### PR TITLE
Add bdcom driver

### PR DESCRIPTION
**Pull request by candlerb**
## Pre-Request Checklist

- [ ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [X] Changes are reflected in the documentation
- [X] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description

Add bdcom.rb driver

Tested with Fiberstore S3900-48T6S-R

See also PR #1855

### CODE REVIEW

**Comment by candlerb** [comment]
CI is broken.  It reports "Publish Docker: All jobs have failed".  If I follow the link it shows this failing step:

```
Run elgohr/Publish-Docker-Github-Action@master
  with:
    name: oxidized/oxidized
/usr/bin/docker run --name e28490ade4c10e1f694cfca540e421186422c1_a450a3 --label e28490 --workdir /github/workspace --rm -e INPUT_NAME -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_REGISTRY -e INPUT_SNAPSHOT -e INPUT_DEFAULT_BRANCH -e INPUT_DOCKERFILE -e INPUT_WORKDIR -e INPUT_CONTEXT -e INPUT_BUILDARGS -e INPUT_BUILDOPTIONS -e INPUT_CACHE -e INPUT_TAGS -e INPUT_TAG_NAMES -e INPUT_TAG_SEMVER -e INPUT_NO_PUSH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/oxidized/oxidized":"/github/workspace" e28490:ade4c10e1f694cfca540e421186422c1
Unable to find the username. Did you set with.username?
```

**Comment by freddy36** [comment]
I would suggest removing the "Reboot history information:" block from "show version".

You might want to save detailes about installed SFP transceivers too.

And maybe add BDCOM as seperate supported vendor with the following products linking to the module:
* S2200 series
* S2200PB series,
* S2200-B series
* S2500-B series
* S2500-C series,
* S2500PB series
* S2500-P series
* S2900 series

**Comment by candlerb** [comment]
> I would suggest removing the "Reboot history information:" block from "show version".

Could do, although it's static until the device next reboots, so I thought it was useful to see - that is, oxidized notifies you when it reboots.

> You might want to save detailes about installed SFP transceivers too.

I couldn't find a show command for this.  Nothing under "show interface", no "show port", "show fiber-ports" etc.  Do you know what the command would be?

> And maybe add BDCOM as seperate supported vendor with the following products linking to the module:
> 
> * S2200 series
> * S2200PB series,
> * S2200-B series
> * S2500-B series
> * S2500-C series,
> * S2500PB series
> * S2500-P series
> * S2900 series

If you know that those are all compatible then yes I'll do that.

**Comment by freddy36** [comment]
I don't think reboot notification is what oxidized is supposed to too. Your monitoring system should be able to detect this by checking the uptime. 

Based on the documentation (S3900 Series Switches Optical Port Additional Function Configuration.pdf) there should be a global "ddm" command to enable DDM.  Then a `show int ge0/X` should show the tranceiver details. Not sure what happens if you remove the specific interface or i the command shows any other interface details. 
BDCOM models are taken from their manual, so they should be fine.

**Comment by candlerb** [comment]
ddm is enabled by default, there's only a command to disable it:

```
ldex-r18-sw2_config#ddm
Incomplete command
ldex-r18-sw2_config#ddm ?
  disable  -- Disable  DDM function
ldex-r18-sw2_config#ddm disable
ldex-r18-sw2_config#no ddm disable
```

I don't actually have any transceivers installed at the moment (I'll try this in next data centre visit).

There is a "show ddm" command:

```
ldex-r18-sw2#show ddm ?
  |         -- Output modifiers
  <cr>
ldex-r18-sw2#show ddm
Current ddm status:Enable
Port      TX(dbm)   RX(dbm)   VOL(V)    BIAS(mA)  TEMP(C)
ldex-r18-sw2#
```

It looks like I'd have to mask out all of those columns apart from the Port, so it's not very useful.

"show interface" shows all interfaces in Cisco-like gory detail:

```
ldex-r18-sw2_config#show int
GigaEthernet0/1 is down, line protocol is down
  protocolstatus upTimes 0, downTimes 0, alloc at 2000-1-1 0:0:18
  Ifindex is 197, unique port number is 1
  Hardware is Giga-TX, address is 649d.99XX.XXXX (bia 649d.99XX.XXXX)
  MTU 9216 bytes, BW 1000000 kbit, DLY 10 usec
  Encapsulation ARPA
  Auto-duplex,  Auto-speed,  Flow-Control Off
  5 minutes input rate 0 bits/sec, 0 packets/sec
  5 minutes output rate 0 bits/sec, 0 packets/sec
  Real time input rate 0%, 0 bits/sec, 0 packets/sec
  Real time output rate 0%, 0 bits/sec, 0 packets/sec
     Received 0 packets, 0 bytes
     0 broadcasts, 0 multicasts, 0 ucasts
     0 discard, 0 error, 0 PAUSE
     0 align, 0 FCS, 0 symbol
     0 jabber, 0 oversize, 0 undersize
     0 carriersense, 0 collision, 0 fragment
     0 L3 packets, 0 discards, 0 Header errors
     Transmitted 0 packets, 0 bytes
     0 broadcasts, 0 multicasts, 0 ucasts
     0 discard, 0 error, 0 PAUSE
     0 sqettest, 0 deferred, 0 oversize
     0 single, 0 multiple, 0 excessive, 0 late
     0 L3 forwards
GigaEthernet0/2 is down, line protocol is down
  protocolstatus upTimes 0, downTimes 0, alloc at 2000-1-1 0:0:18
...
```

**Comment by candlerb** [comment]
With a couple of fibre modules installed, I get:

```
ldex-r17-sw2#show ddm
Current ddm status:Enable
Port      TX(dbm)   RX(dbm)   VOL(V)    BIAS(mA)  TEMP(C)
tg0/49    -1.26     -3.73     3.30      29.19     25.00
tg0/50    -2.36     -0.52     3.30      39.51     28.00
```

That's not very helpful for inventory tracking.  There is more detail in `show interface`:

```
ldex-r17-sw2#sh int tg0/49
TGigaEthernet0/49 is up, line protocol is up
  protocolstatus upTimes 1, downTimes 0, last transition 2021-11-9 13:42:12
  Ifindex is 245, unique port number is 97
  Description: ldex-l3sw1
  Hardware is 10Giga-FX-SFP, address is 649d.99XX.XXXX (bia 649d.99XX.XXXX)
  MTU 9216 bytes, BW 10000000 kbit, DLY 10 usec
  Encapsulation ARPA
  Full-duplex,  10000Mb/s,  Flow-Control Off
Transceiver Info:
    SFP,LC,1310nm,10000BASE-FX-LR,LOS:no
    SM 10KM
    DDM:YES,Vend:FS,PN:SFP-10GLR-31
    SerialNum:G191XXXXXXX,Date:2019-11-01
DDM info:
    TX power:-1.26 dBm, RX power:-3.70 dBm
    SFP temperature:25.00 C,supply voltage :3.30V,Bias Current.:29.16mA

  DDM Thresholds:        Low-Alarm    Low-Warning   High-Warning  High-Alarm
  TX power(dBm):            -9.50        -9.00         2.00         2.50
  RX power(dBm):           -16.00       -15.50         2.00         2.50
  SFP temperature(C):         -45          -40           85           90
  Supply voltage(v):         2.97         3.13         3.46         3.63
  Bias Current(mA):          1.00         1.00       100.00       110.00
  5 minutes input rate 65704403 bits/sec, 18625 packets/sec
  5 minutes output rate 121625669 bits/sec, 12283 packets/sec
  Real time input rate 0%, 62299794 bits/sec, 17352 packets/sec
  Real time output rate 1%, 112996512 bits/sec, 11175 packets/sec
     Received 106034585 packets, 96061778696 bytes
     129825 broadcasts, 492351 multicasts, 105412409 ucasts
     0 discard, 0 error, 0 PAUSE
     0 align, 0 FCS, 0 symbol
     0 jabber, 58541973 oversize, 0 undersize
     0 carriersense, 0 collision, 0 fragment
     0 L3 packets, 0 discards, 0 Header errors
     Transmitted 156897429 packets, 194753185193 bytes
     90 broadcasts, 1301 multicasts, 156896038 ucasts
     0 discard, 0 error, 0 PAUSE
     0 sqettest, 0 deferred, 67807686 oversize
     0 single, 0 multiple, 0 excessive, 0 late
     0 L3 forwards
```

So the transceiver serial number *is* there, but to get it you have to parse a whole bunch of stuff and throw 95% of it away :-(

Sadly, the obvious solution doesn't work:

```
ldex-r17-sw2#sh int | include SerialNum
ldex-r17-sw2#
```

**Comment by freddy36** [comment]
If there's no way to filter the output via include or something else the best Idea probably would be to filter out anything but the intrafec name + "Transceiver Info" block.

**Comment by mortzu** [comment]
Please fix the merge conflict

**Pull request closed without merging**
