### PR TITLE
Hide snmp community

### PR DESCRIPTION
**Pull request by brunobritocarvalho**
Community is displayed next to this line (old ios versions)

### CODE REVIEW

**Comment by ZacharyPuls** [comment]
Won't this remove some valid config?

We could use this RegEx instead:

`cfg.gsub! ^(snmp-server host \S+( vrf \S+)?( version (1|2c|3))?)\s+\S+((\s+\S*)*)\s*, '\\1 <secret hidden> \\5'`

Test inputs:

`snmp-server host 10.10.25.5 version 2c net.ksfiber.configmgmt config `
`snmp-server host 10.10.25.5 net.ksfiber.configmgmt config `
`snmp-server host 1.2.3.4 vrf Mgmt-intf version 2c test  mpls-vpn `
`snmp-server host 1.2.3.4 test `
`snmp-server host 1.2.3.4 test mpls-vpn aaa_server `

Test outputs:

`snmp-server host 10.10.25.5 version 2c <secret hidden> config`
`snmp-server host 10.10.25.5 <secret hidden> config`
`snmp-server host 1.2.3.4 vrf Mgmt-intf version 2c <secret hidden> mpls-vpn`
`snmp-server host 1.2.3.4 <secret hidden> `
`snmp-server host 1.2.3.4 <secret hidden> mpls-vpn aaa_server`

**Comment by brunobritocarvalho** [comment]
I did not encounter those examples when I looked at my config files, but your regex does sound a lot better. My main concern was to remove those community ASAP, guess I did not spend enough time looking at it, thanks a lot!

**Comment by laf** [comment]
@brunobritocarvalho you updating this PR?

@ZacharyPuls thanks for the input :)

**Comment by brunobritocarvalho** [comment]
@laf guess it should work now, I'll test it tomorrow, sadly I can't do it tonight. Thanks guys.

**Comment by laf** [comment]
@ZacharyPuls You happy with this?

@brunobritocarvalho Ace, if you can confirm that would be great.

**Comment by brunobritocarvalho** [comment]
Hey guys, just tested today, we have this use case still appearing: 

+snmp-server host $IP $PASSWORD

So Zachary's regex does not entirely work in our context. As for the other scenarios, it looks alright.

**Comment by ZacharyPuls** [comment]
@laf Looks good to me!
@brunobritocarvalho
I just tested this again on regexr, this should be working, here's what I'm getting: https://screenshots.firefox.com/HG72yFnrAvA05whu/regexr.com

Thanks for adding in the /^/ for me, forgot to add it back when pasting from the RegEx tool.

**Comment by laf** [comment]
@ZacharyPuls Thanks :D

@brunobritocarvalho Let me know when this is updated to the final version.

**Comment by zombah** [comment]
Maybe it is possible to make this change as additional version of ios.rb like "extra secure ios"?
For example i have miriad of different communities on my ios devices and i will need to make my own version after this change, to not hide communities, because i need to backup them and track their changes.

**Comment by brunobritocarvalho** [comment]
@zombah sounds like an idea, any idea how to do it, I am no ruby expert sadly. 
Would it be something like this? 
`  cmd :extra_secure do |cfg| 
    cfg.gsub! /^(snmp-server host \S+( vrf \S+)?( version (1|2c|3))?)\s+\S+((\s+\S*)*)\s*/, '\\1 <secret hidden> \\5'
    cfg
  end 
`
@ZacharyPuls I tested the regex again, it does seem to work, don't know why it failed last time. : 
`cfg = 'snmp-server host 127.0.0.1  Psdadasdasw2123123'
cfg.gsub! /^(snmp-server host \S+( vrf \S+)?( version (1|2c|3))?)\s+\S+((\s+\S*)*)\s*/, '\\1 <secret hidden> \\4'
puts cfg
`

**Comment by laf** [comment]
Personally (not the projects stance). Having more config options for things like this seems ott. We already have the secure config option which if set is where this change affects so if you want to see communities then you shouldn't set the secure flag.

I do realise that what should be classed as 'secure' is subjective but this model already removes the communities from other config lines so to me this seems like it was just missed in the first place.

**Comment by brunobritocarvalho** [comment]
@laf Makes sense, that's also what I thought at first. As for me, I think everything is fine now, the existing code should work fine.

**Comment by zombah** [comment]
Ok i'll go for "remove_secret: false" then

**Pull request merged**
