### PR TITLE
Add group mapping

### PR DESCRIPTION
**Pull request by mjbnz**
## Pre-Request Checklist

- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [x] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description

Add the ability to map group aliases to group names. This is useful when a data source doesn't have a simple field for grouping, but does have another that can be combined. (For example, in Netbox this allows for multiple tennants to be grouped together)

### CODE REVIEW

**Comment by mjbnz** [comment]
This branch is on top of my 'rubocop-fixes' branch, hence the extra commits.

**Comment by mortzu** [comment]
Can you reflect the change in the documentation please?

**Comment by mjbnz** [comment]
> Can you reflect the change in the documentation please?

Done

**Comment by mortzu** [comment]
Please fix the merge conflict

**Pull request merged**
