### PR TITLE
fixes ArubaOS-CX enviroment/system inconsistent values #2297

### PR DESCRIPTION
**Pull request by raunz**
## Pre-Request Checklist

- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [x] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
Removed always changing Up Time/CPU/Memory lines from 'show system' with command enchancement.
Replaced temperature and fan RPM values with <hidden> string avoid minor changes but to keep the model/component technical information.

Closes issue #2297

### CODE REVIEW

**Comment by danpoltawski** [comment]
Could you rebase this :)

**Comment by jmurphy5** [comment]
I put in #2379 to do remove the show environment fully. The Uptime, CPU, and Memory filter are a great catch @raunz !

**Comment by mortzu** [comment]
Can you please resolve the conflict?

**Comment by raunz** [comment]
> Can you please resolve the conflict?
Done.

**Pull request merged**
