### PR TITLE
Feature - Lockout by IP address

### PR DESCRIPTION
**Pull request by jsynack**
This implement a simple lockout by IP address methodology that the end-users can do when needed. 

This checks for a file in the lockout directory based on the IP address of the node about to be polled.
Only single IPs are locked, there is nothing fancy such as CIDR-based locking (yet).

If the file exists, the node is skipped for that polling interval/cycle. 

This allows for things to be locked out (not polled) in the event the user knows a node is going to be unreachable for some time - but doesn't want the polling and retries to build up on the offline nodes.
This also allows other things (such as external NMSes) to trigger a lockout etc as long as they have read/write to the lockout file directory (controlled by `lockout_directory:` configuration directive).

There were multiple ways to implement this - this seemed like the easiest/safest way for ease of use. There could be some impact to how job timing is calculated, since the job for a locked node is over instantly. 

Since this introduces a new status of `:locked` - I also will send in a PR for oxidized-web to see this status and render things properly in the UI.

Comments/feedback welcomed. I have had this sitting for a while - and trying to get it eye-ball checked by others or any different directions/thoughts.

### CODE REVIEW

**Comment by jsynack** [comment]
I forgot to mention - this also implements the changes from PR #1327  . So that one could be closed if this one is taken.

**Comment by ytti** [comment]
Can you do separate PR fo the jobs_done. I'm not sure about the lockout implementation. I think I prefer another Asetus instance (and consequently file) with array of IPs, names, but perhaps I misunderstand problem and current implementation may better address is.

**Comment by ytti** [comment]
If it were instance of Asetus, we could POST/GET update it via oxidized-web, and then #save the Asetus instance to get it to disk too.

**Comment by jsynack** [comment]
I havent looked much as the Web-i-fication aspects - but it does make sense to make it API-able and save the config out for large lockouts.

I will play around with some asetus-style methods and see what I can come up with.

**Comment by mortzu** [comment]
any news on this?

**Pull request closed without merging**
