### PR TITLE
Better/more unified precedence for options that can be defined global, per model, group or per node

### LINKED ISSUE #3058: Model settings preferred over group settings
Hi Guys,

I have deployed Oxidized and it is working great except for one of the things where the model settings are preferred over group settings. I am using groups just to categorize the devices based on internal departments and then the models are used for vendor/model specific settings/creds as those are fairly consistent across departments. However, there is one group(or department) where the creds for specific model (in this case asa) are different. I want the group settings to be preferred for that model. But it seems that the creds defined under model are being used instead.

Here is my config file ->

```
---
username: uname
password: 12345
model:
resolve_dns: true
interval: 3600
use_syslog: true
log: /home/oxidized/.config/oxidized/logs/
debug: false
threads: 30
use_max_threads: false
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
    user: oxidized
    email: oxidized@oxidized.local
    repo: "~/.config/oxidized/oxidized.git"
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 2
      username: 3
      password: 4
groups:
  Department1:
    models:
      asa:
        username: dpt1user
        password: dpt1pass
        vars:
          enable: dpt1enable
models:
  ios:
    username: uname
    password: 12345
    vars:
      enable: 56789
  asa:
    username: uname
    password: 12345
    vars:
      enable: 56789
  panos:
    username: panuser
    password: panpass

```
router.db file -->

Device1:asa:Department1
Device2:ios:Department1
Device3:panos:Department1
Device4:asa:Department2
Device5:ios:Department2
Device6:panos:Department2
Device7:asa:Department3
Device8:ios:Department3
Device9:panos:Department3

Logs -->
Department1/Device1 status no_connection, retry attempt 1
10.10.10.10 raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user uname@10.10.10.10"
Department1/Device1 status no_connection, retry attempt 2
10.10.10.10 raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user uname@10.10.10.10"
Department1/Device1 status no_connection, retry attempt 3
10.10.10.10 raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user uname@10.10.10.10"
Department1/Device1 status no_connection, retries exhausted, giving up

Here Device1 should use creds dpt1user/dpt1pass but it still uses uname/12345. 
Any suggestions on what I am missing or how I can make this work?

### PR DESCRIPTION
**Pull request by EinGlasVollKakao**
## Pre-Request Checklist

- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [x] Tests added or adapted (try `rake test`)
- [x] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
Hey,

with this PR options that are resolved when creating the node (like credentials, etc.) behave the same way as variables (`lib/oxidized/config/vars`), which means that group options are now preferred over model options and there's now also the possibility to define these options model specific in a group, which is already possible with [variables](https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#advanced-group-configuration).

This would help with my scenario in which nearly all devices with the same model have identical credentials, but a small group of those have different ones. First I thought that this would be possible with groups, but in the current state I didn't find a way to achieve this.

This PR also adds a section in the documentation in which I try to explain this hierarchy for options, which should make this behavior easier to understand. 

also fixes #3058

### CODE REVIEW

**Comment by ytti** [comment]
This looks good and useful to me. But I didn't test or try it.

**Comment by ytti** [comment]
@robertcheramy take a gander at this, and merge if you also think it's fine. It's pretty substantial change so I wanted additional eyes on it. But no pressure, if it breaks something, we'll fix it, I'm happy to commit time on fixing this if it breaks.

**Comment by robertcheramy** [comment]
I've struggled a bit with the idea of removing duplicate code between Oxidized::Node and Oxidized::Config::Vars, but this code refactoring is not related to this PR and can be done later.

Thank you for this very good PR, including unit tests.

There are a few things that I want to change (empty spaces at the End of line, position of log in CHANGELOG.md) so I'll merge directly with git into master.

**Comment by robertcheramy** [comment]
This PR have been Manually rebased and merged into master (commits 60dd78672bfa6f78c6b159f50b4cc08acd081d1e -> fc7990ddfaaf0f2041f17faeff7797ba2752a486)

**Pull request closed without merging**
