### PR TITLE
all nodes done hook

### LINKED ISSUE #178: Another event for Hooks, worker_done
Can we add another event for hooks that will trigger when the worker is done with its current job cycle?  I hope this makes sense and I am using the correct terms.

Example: Every time oxidized goes out and pulls configs for all the devices in router.db, this event would trigger at the end of that process.

### PR DESCRIPTION
**Pull request by danilopopeye**
This PR includes a new event `nodes_done` for a complete cycle.

Example of a run:

```
D, (...) loads of logs lines (...)
D,  lib/oxidized/node.rb: Oxidized::SSH ran for 10.X.X.206 successfully
D,  lib/oxidized/job.rb: Config fetched for 10.X.X.206 at 2017-08-15 14:50:54 UTC
D,  lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 3 of 3
D,  lib/oxidized/worker.rb: Running :nodes_done hook
D,  Exec: Execute: "env >> /tmp/nodes_done.log"
D,  lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 3
D,  lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 3
```

closes #178

### CODE REVIEW

**Comment by laf** [comment]
@danilopopeye LGTM.

**Comment by danilopopeye** [comment]
@ytti @aakso any considerations? can I merge this one? 😄

**Comment by aakso** [comment]
Looks good, this has been requested before

**Comment by danilopopeye** [comment]
well 2 out of 3 approvals seems enough 😄

**Pull request merged**
