### PR TITLE
This adds support for D-Link switches

### PR DESCRIPTION
**Pull request by rfdrake**
This specifically supports DES-3526/3550 series switches.

### CODE REVIEW

**Comment by ytti** [comment]
Dlink really has no OS name?

**Comment by rfdrake** [comment]
They've got several switch models but I'm not sure if the firmware has 
an actual OS name.  The firmware for the switches was labelled like this:

des3550_firmware_501b65.had

Even looking at a few of the newer switches, they don't appear to name 
the OS.

**Comment by ytti** [comment]
But the newer will also work with this model? And big Dlink too? Or just 'DES' Dlinks? If just DES, it might be prudent to add that to the model name, so it does not become confusing when new Dlink switch is added.

However if all are under same OS now, I'm happy to accept this too. It's just that I won't guarantee I won't change names later, if it's named non-uniquely, but that may be better option now, than to invent bad unique name, due to lack of clear commonly understood name (which is bound to happen, when new software emerges from same vendor).

**Comment by rfdrake** [comment]
It should work with the newer models and the big dlink switches. I've 
checked and the CLI is the same across their models.  If anyone tries it 
and it fails I'll try to fix it up so it works.

**Pull request merged**
