### PR TITLE
Store stats in SQL, and use it to re-build ring queue. Need sqlite3.

### PR DESCRIPTION
**Pull request by FlorianDoublet**
Store stats in SQL, and use it to re-build ring queue. Need sqlite3.

### CODE REVIEW

**Comment by ytti** [comment]
Quickly looking I'm not sure we're threading anymore, as the collection appears to be outside the thread in job.rb, I think it'll block until finished then thread just collects information from hash.

I'm also wondering if we should use Sequel ORM instead of raw SQL.

**Comment by FlorianDoublet** [comment]
I know what you mean. It's a good question, but after all, it's the tread who call Store, so are you sure we're not threading anymore ? And is there a way to be sure ? 
I can calculate it just as before and then send it to Store, but it was to minimize the lines.

I can't tell you if Sequel ORM is better than raw SQL, I don't know it. But SQLite is a kind of reference for program database, no ?

**Comment by ytti** [comment]
I don't think it's thread which calls the store. Only the 'super do' part is threaded, outside it, it'll block, I'm pretty sure.
There is way to be sure, set rotation time so small that single thread won't do it. And with debugging on, it should report how many threads running and how many wanted.

**Comment by FlorianDoublet** [comment]
Hum true, but if it's just the problem moving the call of Store into super should fix it. I will check for it

**Comment by ytti** [comment]
SQLite also itself does not support multiple writes, so the code probably isn't thread safe, as many threads try to connect to the same SQLite database, the one doing it right now, will block it.
It might be better for thread to just return config/status, and then the main thread handle all the SQL work alone, then there is no competition to the SQL data.

Except of course if WWW side wants to write there at the same time, then you'll need to implement mutex locking.

**Comment by FlorianDoublet** [comment]
What do you call "main thread", the class Core ?

**Comment by ytti** [comment]
Main thread is the thread which starts all the jobs, walks through job list etc, essentially the worker.

It checks if enough jobs are running, collects stopped jobs and handles their output. This worker could handle the config storing of threads.

**Comment by FlorianDoublet** [comment]
Ok thanks a lot. And so, we don't need a mutex I guess if Worker handle sql injection ?

**Comment by ytti** [comment]
No. Unless oxidized-web tries to write to the SQL as well, then we'll need to mutex locking there.

**Comment by FlorianDoublet** [comment]
Updated, hope it's better

**Comment by MrRJ45** [comment]
@ytti @FlorianDoublet

Does this need testing? If so I will implement the changes tomorrow.

**Comment by FlorianDoublet** [comment]
It's normally alright.

**Comment by ytti** [comment]
I've been lazy, I've not really reviewed the latest version. I'll try to get to it. I also kind of would like to refactor the oxidized core stuff (node, nodes, worker, manager...) but it seems unlikely I'll find time any time too soon.

**Comment by MrRJ45** [comment]
I've just implemented this, so I'll let you know of any issues :)

Only problem so far is it couldn't create the SQLite DB, I changed config.rb to this and that resolved it:

```ruby
CFGS.default.database      = File.join(Config::Root, 'oxidized_database.db')
```

**Comment by FlorianDoublet** [comment]
Oh sorry,  I didn't have this issue..  Thanks for your  review!

**Comment by MrRJ45** [comment]
I guess its probably fine it your DB already exists, I didnt create it first, so I think the issue is only when it tries to create the empty DB :)

**Comment by MrRJ45** [comment]
@FlorianDoublet Just to give you a heads up I am seeing an issue with this patch at the moment, see Issue #177

**Comment by ytti** [comment]
I really should focus on this. But I can't accept it right now. This is not the implementation I'm exactly looking for. Sorry, I know it was lot of work. Direction is where I want to go, but implementation details are not.

**Comment by danilopopeye** [comment]
@FlorianDoublet thanks again for the time and code 👏 I'm closing this as is too outdated to be merged easily 😐

**Pull request closed without merging**
