### PR TITLE
Implement two fixes in ASA model behavior

### PR DESCRIPTION
**Pull request by jsynack**
1. Fix for Issue #741 

 Some ASAs / revs will jitter the 'configuration last update' time even when there has not been a configuration change.

 Trim off the msec and seconds to avoid most jitter scenarios as a compromise but still retain the last configuration modification hour and minute.

 credit to @ecm75 for the adjustment.

This will shows a diff for any installed base of ASA devices due the msec and seconds being trimmed out.

Closes ytti/oxidized#741

2.  Implement PR #1071 in a slightly different fashion.

Failover information gathering commands added, wrapped in a test of the failover active status from the 'show failover' command. 

 credit to @ik5pvx for the desired command list and original PR.
 
 The 'headers' are added so that it is clear the next command is reporting information on the firewall mate. 

 Devices that do not have Failover active will not have any additional commands run.

Both have been tested on various ASAs in production environment.

### CODE REVIEW

**Comment by pv2b** [comment]
Before looking at the report, I already imagined the edge case where it would jitter at a minute boundary, which @jsynack already mentioned in #741:

>While there is the edge case that a jittering second could 'flip' the minute - it is probably not worth the extra code to handle that case.

If we want to go even further down, imagine saving a configuration exactly on midnight on Jan 1 of a year. Then you'd get jitter on every single component of the date!

After thinking about this, I come to the conclusion that it's probably mathematically impossible to completely handle this bug in the Cisco code without looking at the previous commited output.

If this bug has been fixed in more recent Cisco software - perhaps the "correct" fix is to have a flag to completely omit this date? Even so, this will still work fine approximately 98.3% of the time so it's probably better than nothing.

**Comment by jsynack** [comment]
Great points @pv2b  - 

In general my thinking was to solve for the cases that I had seen with my installed base of ASA units that had experienced this issue ("more than 500 - less than 1000") .  I had not seen a minute jitter in the sample size I had.

There is certainly the ability to chop out the timestamp completely - it was an attempt to have a compromise and retain *some* information from it :)   Didn't want to spoil it for everyone unless it was a much larger issue. 

Since it was an easy adjustment that we had made locally I didn't collect any more stats on it. There doesn't seem to be much other report of it from the oxidized community - and the software revs are older where we have seen this The defect is slowly going away.

I thought about 'checking' the device as you describe - execute the command multiple times and observing the result - but opted not to do it to avoid punishing the majority of units that don't have this problem and punishing the AAA server with more commands to authorize per `interval` :)

**Comment by laf** [comment]
I'll get this tested pretty soon. Sorry for the delay @jsynack and thanks for the PR though.

**Comment by laf** [comment]
Jitter correction works fine from what I can see.

I'm going to let the failover side run for a bit longer to see if it generates noise but so far seems pretty good as well.

**Comment by laf** [comment]
@jsynack So I've tested the failover command being in it as well and it does flip between not being able to get the state and working fine. I don't think that's an issue on our setup and happens across a good number of devices.

Have you seen any issues on your side?

**Comment by jsynack** [comment]
@laf - So you see differences/diffs between different oxidized runs on the device as it can get the failover info and not get the information on other runs? (information churn).

We have not seen any problems/churn and have been running with this deployed as our `asa.rb` since the original PR timeframe - Roughly mid Nov-2017.  As a percentage of our ASA deployments - HA/FO is not that large as compared to other vendors/models - so it may simply be that we do not have the critical mass with ASAs or version-specific items.

Do you have any AAA logs of what commands get run or any debug log of the session?  Does it work clean on any units ? Break always on specific units?

**Comment by laf** [comment]
@jsynack I'll have to do some more testing to find out. Leave it with me.

**Comment by wk** [comment]
@jsynack is this PR abandoned? Can it be closed?

**Comment by jsynack** [comment]
I am just about to get our instances caught up to `master` in the next few days - and I will see where things land and give it another go. For cleanliness - this can be closed out and I will open a new one for any changes.

**Comment by mortzu** [comment]
Can you please fix the conflicts

**Pull request closed without merging**
