### PR TITLE
Added some API documentation

### LINKED ISSUE #940: Additional hooks for API calls
I'm proposing an additional `post_store` hook, if the configuration pull was initialized through an API call (`/node/next/[node_name]`).

The scenario I'm thinking of is this: 
Oxidized has a scheduled run once a day (at night for example). Changes found during these scheduled runs should trigger a notification script through the `post_store` hook and inform us about undocumented changes (it could be a security issue).

Now, during work hours, configuration changes are made by an admin and an API call is issued to Oxidized after logout from the switch (`/node/next/...`) . This change should not trigger the `post_store` hook, because this change is wanted and will be documented. So an additional `post_store` hook is needed which only applies to API calls. Also, the post_store hook needs to know it was not triggered by the API.

Is this something others would want? I'm trying to figure out how this could be done in the code, but I'm fairly new to Ruby, so I can't make any promises for a PR 🙁 Trying my best, though!

The possibility to edit the commit message while doing the API call would be nice (maybe by using a HTTP header?), but that's just wishful thinking.

### PR DESCRIPTION
**Pull request by mrplow87**
Added restful API documentation and fixed the mention of commit user and message in the introduction.

closes #940

### CODE REVIEW

**Comment by laf** [comment]
This is definitely needed but imho I think we should start splitting the readme out, this is prime to be put in a new file.

@ytti  / @danilopopeye - Thoughts?

**Comment by mrplow87** [comment]
Also, if we split it into additional files, shouldn't this be moved to oxidized-web?

**Comment by laf** [comment]
I guess although I think most people end up here.

**Comment by danilopopeye** [comment]
> This is definitely needed but imho I think we should start splitting the readme out, this is prime to be put in a new file.

yeah, I was thinking about this yesterday. haven't decided how to do it yet.



> Also, if we split it into additional files, shouldn't this be moved to oxidized-web?

i guess we could move this doc to oxidized-web and include a link in the readme here?

**Comment by laf** [comment]
> i guess we could move this doc to oxidized-web and include a link in the readme here?

Seems sensible.

**Comment by danilopopeye** [comment]
@mrplow87 could you reopen this changes to oxidized-web? Then we can link it here.

**Pull request closed without merging**
