### PR TITLE
Model for zte olt c3xx

### PR DESCRIPTION
**Pull request by glaubway**
## Pre-Request Checklist

- [ ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [x] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
model for zte olt c3xx
working with firmware 1.2.5 and 2.1

### CODE REVIEW

**Comment by wk** [comment]
Same here as in #2119 - needs a bit of documentation, but looks good! It's also always great to know what's the name of the underlying OS (unless its literally called ZTEOLT), as that would allow to map additional variations to this model in the future.

**Comment by glaubway** [comment]
> Same here as in #2119 - needs a bit of documentation, but looks good! It's also always great to know what's the name of the underlying OS (unless its literally called ZTEOLT), as that would allow to map additional variations to this model in the future.

Hi, soon i will add model for ZTE switches it have some different with command in ZTE olt model.

**Comment by wk** [comment]
Pulling this one in as well, thanks!

**Comment by edielson** [comment]
in the router.db file, I set it up like this
LOGTEL-ZTE-ARARAS: 10.200.1.1:zteolt:zteolt::2334

I use telnet protocol to make the connection

and it is showing the following error in the log

10.200.1.1 raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"
zteolt/LOGTEL-ZTE-ARARAS status no_connection, retry attempt 1


in file config 

source:
  default: csv
  csv:
    file: /opt/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      group: 3
    vars_map:
      ssh_port: 4
      telnet_port: 5

**Comment by glaubway** [comment]
Hi, what zte device you have? This model tested only on zte olt c320 and c300.
Could you share debug log, looks like there unable catch the prompt.

**Comment by edielson** [comment]
ZXAN product C300 of ZTE Corporation

**Comment by edielson** [comment]
System Description: C300 Version V2.1.0 Software, Copyright (c) by ZTE Corporation Compiled

**Comment by edielson** [comment]
I'm using https://github.com/glaubway/oxidized/blob/glaubway-zteolt/lib/oxidized/model/zteolt.rb

**Comment by edielson** [comment]
Apr 14 14:24:34 host.myrouter.com.br oxidized[27029]: 10.200.1.1 raised Errno::ECONNREFUSED with msg "Connection refused - connect(2) for 10.200.1.1"
Apr 14 14:24:34 host.myrouter.com.br oxidized[27029]: lib/oxidized/node.rb: Oxidized::SSH failed for LOGTEL-ZTE-ARARAS
Apr 14 14:24:34 host.myrouter.com.br oxidized[27029]: lib/oxidized/input/cli.rb: Running post_login commands at LOGTEL-ZTE-ARARAS
Apr 14 14:24:34 host.myrouter.com.br oxidized[27029]: lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x00005600c90b0228@/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/model/zteolt.rb:40> at LOGTEL-ZTE-ARARAS
Apr 14 14:24:34 host.myrouter.com.br oxidized[27029]: Telnet: enable @LOGTEL-ZTE-ARARAS

**Comment by edielson** [comment]
Apr 14 14:32:10 host.myrouter.com.br oxidized[27132]: lib/oxidized/input/cli.rb: Running post_login commands at LOGTEL-ZTE-ARARAS
Apr 14 14:32:10 host.myrouter.com.br oxidized[27132]: lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x0000555a28c81220@/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/model/zteolt.rb:40> at LOGTEL-ZTE-ARARAS
Apr 14 14:32:10 host.myrouter.com.br oxidized[27132]: lib/oxidized/input/ssh.rb enable @ LOGTEL-ZTE-ARARAS with expect: /^[pP]assword:/
Apr 14 14:32:10 host.myrouter.com.br oxidized[27132]: lib/oxidized/input/ssh.rb: expecting [/^[pP]assword:/] at LOGTEL-ZTE-ARARAS

**Comment by glaubway** [comment]
Hmm, okay, maybe I know why oxi can't catch the prompt...
I no longer have access to zte devices so can't debug and fix it, but think that the following workaround may help you.
So you need to add to your csv mapping "enable" vars
```
    map:
      name: 0
      ip: 1
      model: 2
      group: 3
    vars_map:
      ssh_port: 4
      telnet_port: 5
      enable: 6
```
And if your device have enable just add it to your source file, if no add "nil".

**Comment by glaubway** [comment]
If I remember it right there was problem if device haven't "enable" password but in config you have enable var with no nil value, so when oxi connecting to zte device it send "enable" and waiting for something and no pass to next post_login.
```
cfg :telnet, :ssh do
    # preferred way to handle additional passwords
    post_login do
      if vars(:enable) == true
        cmd "enable" /// send and not pass to next post_login
      elsif vars(:enable)
        cmd "enable", /^[pP]assword:/
        cmd vars(:enable)
      end
    end
    post_login 'terminal length 0'
    pre_logout 'disable'
    pre_logout 'exit'
  end
```
But if on device you need to enter "enable" password and you have enable var that model will work correctly.
Maybe someone could fix this issue or just use workaround that I provide above...

**Comment by edielson** [comment]
thank you very much I added the enable password and it worked

**Pull request merged**
