### PR TITLE
Don't post diff to Slack if there are no diffs

### LINKED ISSUE #1150: Slackdiff hook throws error when there is no diff
Hello,

I started oxidized for the first time, using CSV source, and git output. I configured the slack hook, and I received the below error.

```
[2018-01-16T22:08:02.817068 #15] ERROR -- : Hook slack (#<SlackDiff:0x000055c35b519c98>) failed (#<TypeError: no implicit conversion of Symbol into Integer>) for event :post_store
```

I investigated a little bit and it seems when [this line](https://github.com/ytti/oxidized/blob/master/lib/oxidized/hook/slackdiff.rb#L36) runs, it throws a TypeError seen above

I used `diff.inspect` to see what was up and it showed just `no diffs` instead of a hash. This makes sense as the configuration hasn't changed from what was on the remote, however I did not even have `diff` turned on for the Slack hook.

Looks like there needs to be a check to only post when there is a diff.

### PR DESCRIPTION
**Pull request by yzguy**
If there are no diffs then do not try to post to Slack.

Fixes #1150

### CODE REVIEW

**Comment by laf** [comment]
I responded in your issue asking to see the config for you slack hook, would you mind posting it so we can see.

**Comment by laf** [comment]
I'm not sure this might be the best place for this, it may be better suited before the hooks are called so we don't run post_store hooks if we have no diff. For now I'll merge this in though.

**Comment by yzguy** [comment]
I agree. At least this fixes the bug at the moment. I don't mind looking into moving some validations back up into `lib/oxidized/hook.rb`.

**Comment by laf** [comment]
Every help we can get is appreciated, especially with the code side of things :)

**Pull request merged**
