### PR TITLE
GPG bug fix

### PR DESCRIPTION
**Pull request by elmobp**
Fixes https://github.com/ytti/oxidized/issues/1082

### CODE REVIEW

**Comment by laf** [comment]
Tested fine.

I do get prompted for the passphrase again when loading oxidized but from what I've found, this is because of gpg2: https://github.com/ueno/ruby-gpgme/issues/11

**Comment by mikenowak** [comment]
Unfortunately this breaks the csv processing altogether.

```
I, [2017-11-23T05:40:58.509504 #5355]  INFO -- : Oxidized starting, running as pid 5355
I, [2017-11-23T05:40:58.639560 #5355]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
E, [2017-11-23T05:40:58.641738 #5355] ERROR -- : node {:name=>"/root/.config/oxidized/router.db", :model=>nil, :username=>nil, :password=>nil, :vars=>{:ssh_port=>nil}} is not resolvable, raised Resolv::ResolvError with message 'no address for /root/.config/oxidized/router.db'
I, [2017-11-23T05:40:58.641831 #5355]  INFO -- : lib/oxidized/nodes.rb: Loaded 0 nodes
F, [2017-11-23T05:40:58.641938 #5355] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
source returns no usable nodes
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:15:in `initialize': source returns no usable nodes (Oxidized::Core::NoNodesFound)
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/cli.rb:12:in `run'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:22:in `load'
	from /usr/local/bin/oxidized:22:in `<main>'
```

**Comment by laf** [comment]
@mikenowak thanks for spotting that. I've just pushed #1113 which fixes this.

@elmobp I think #1113 now breaks gpg support again though, I had a play around trying to get it working but couldn't figure it out - would you mind taking a look?

**Comment by elmobp** [comment]
Ill have a poke over the weekend!

**Comment by laf** [comment]
@elmobp thanks.

**Pull request merged**
