### PR TITLE
use different path for debug logging

### PR DESCRIPTION
**Pull request by skoef**
When I try to run oxidized as a different user, I get permission errors
for oxidized tries to write debug logs (e.g. true-telnet) in current
working directory which in my case is not writable for the
non-privileged user. I think this can be improved by this change.

1) Why would you use CFG.input.debug?.to_s (which in this case will
always be ‘true’) as a prefix at all
2) let’s use the crash directory for the debug output, as we know this
is available and choose a more descriptive name

### CODE REVIEW

**Comment by ytti** [comment]
So CFG is instance of Asetus object. Asetus will always return something for any method. If configuration option does not exist, it'll create it.
Question mark, is not idiomatic use of ruby method naming, it's not returning boolean value. It'll return nil if config exists or config value if it exists. #to_s just guarantees it's string, which may be useless.

Basically I like your change, but it means we no longer can decide the name or location for the file. Maybe that is not a problem.

@nickhilliard has been thinking about this lately, I'd like to hear if he thinks this makes situation better, i think it does.

**Comment by nickhilliard** [comment]
it's better, yes, but it still doesn't solve the problem that there are too many log files.  oxidized shotguns debug log files all over the place and this makes it troublesome to handle via traditional log rotation / analysis mechanisms.  It would be helpful to implement a mechanism to coalesce these log files into a single channel which could be diverted to e.g. syslog / file / stderr, etc.  Also, see #196, which is probably relevant to this patch.

**Comment by skoef** [comment]
Perhaps removing the `#{@node.ip}` from the filename could be a workaround until syslogging or whatever is implemented?

**Comment by ytti** [comment]
I like the @node.ip, I think it's useful.

**Comment by ytti** [comment]
I'll merge this, I'll figure out docs later (I won't).

**Pull request merged**
