### PR TITLE
Added SG support to ciscosmb.rb model

### PR DESCRIPTION
**Pull request by Atroskelis**
Adapted for SG series, not sure about SF. Tested on SG200 with default config. 

Please test.

### CODE REVIEW

**Comment by ytti** [comment]
I thnk we need also 'terminal datadump 0', having invalid command won't hurt, but I think the other, older SMB version won't do 'term len 0'.

**Comment by ytti** [comment]
And probably no reason to remove terminal width, right?

**Comment by Atroskelis** [comment]
You are right, it will run commands nonetheless  and the invalid commands wont affect it. I shall modify it accordingly.

**Comment by Atroskelis** [comment]
The 'terminal width' command isnt available for me, hence it's removal. I readded it, just in case 

```
D18-5u#terminal 
  length  Terminal length
  no      negate the command history function
```

**Comment by ytti** [comment]
The whole point of this exercise is, that there are two distinct SMB boxes. Another of them, does not use SSH auth at all, but always allows SSH users in, and then presents CLI auth. Another of requires SSH auth.
And this isn't only difference between them, there is also the pager disabling difference, and pretty sure the width difference.

Unfortunately I don't have access to either of these devices, so I cannot verify, but I trust that the newest modifications make it work for both.

**Comment by Atroskelis** [comment]
For further reference, i tested this on Cisco Sx220 Series Switch Software, Version 1.0.0.17

**Pull request merged**
