### PR TITLE
Fix Jobs Problem

### PR DESCRIPTION
**Pull request by MrRJ45**
Slight change to fix Jobs Problem I reported in Issue #177

### CODE REVIEW

**Comment by MrRJ45** [comment]
Just to confirm, I've seen the same issue on a clean install of 0.8.1 with none of the SQL code in place.

**Comment by ytti** [comment]
I don't think this works correctly.

When you call #get you rotate the queue. If the interval has not passed, you're next time looking at the next box, which probably has newer timestamp.

We should always check if the oldest box needs to be fetched or not, if not, then we shouldn't rotate, in order to keep oldest on 'top'

**Comment by MrRJ45** [comment]
Reading nodes.rb it looks like returns the top node and moves it to the end of the array?

For some reason its not trying all devices for us and the only way I've found to fix this is to change the way the jobs are picked.

**Comment by ytti** [comment]
The point with #first is that it's non-destructive, it does not change the array. So we 'peek' if next node in array, should be  fetched (has interval passed). If interval has not passed, we don't want to rotate the array, as then we'll get even 'fresher' node on top of the array. So we want to keep the 'freshest' on top of the array.

**Comment by ytti** [comment]
Should I close this, or? Because this is not working. I can explain offline if needed.

**Comment by MrRJ45** [comment]
Feel free to close this :)

I think this was only needed with my persistent storage code

**Pull request closed without merging**
