### PR TITLE
Adds support for Mellanox Switch devices

### PR DESCRIPTION
**Pull request by Ham5ter**
Tested with SX60xx but it should work with other "MELLANOX-OS" Devices to.

### CODE REVIEW

**Comment by ytti** [comment]
Can you update README.md as well about supported OS.

Is the OS name 'MLNX' we prefer to use OS name as class/filename. But sometimes no OS name is published, just wanted to confirm.

**Comment by ytti** [comment]
ping

**Comment by Ham5ter** [comment]
The OS Name is MLNX-OS
I will update this soon.

Thank you for the Reminder.

**Comment by ytti** [comment]
Constants In Ruby cannot include '-' character.

You could name it MlnxOs or MLNXOS or MLNX_OS

**Comment by ytti** [comment]
pong

**Comment by Ham5ter** [comment]
Made the requested changes.
Also I wanted to say thank you for this great Project :+1:

**Comment by ytti** [comment]
Many thanks!

**Pull request merged**
