### PR TITLE
aosw.rb - Update prompt 

### PR DESCRIPTION
**Pull request by davama**
## Pre-Request Checklist

- [ ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [ ] Changes are reflected in the documentation
- [ ] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description

Propose this prompt instead:

^([\w\(.@-]+(\)?\s?)[#>]\s?)$

https://rubular.com/r/kTbM6HlCeBxPiu

Possible fix for https://github.com/ytti/oxidized/issues/1254

### CODE REVIEW

**Comment by davama** [comment]
Proper PR now :smile:

**Comment by wk** [comment]
Thanks! Could you add a line to `CHANGELOG.md` for this change as well to users of the aosw.rb model are aware of it?

**Comment by davama** [comment]
@wk 
Hope im doing this right....

@mikebryant  @vppencilsharpener  @thanegill @boudreau  @cppmonkey @ogarraux @fstern @yeled 

*FYI*

**Comment by wk** [comment]
Looks good to me, since this was, due to #1820, already in for a while unintentionally - I see no reason to delay this PR further; pulling this in.

**Pull request merged**
