### PR TITLE
Create alteonos.rb for radware/alteon 

### PR DESCRIPTION
**Pull request by sfini**
Added support for Radware/Alteon Application Switch

### CODE REVIEW

**Comment by sfini** [comment]
Changed name and made an update for matching with librenms

**Comment by laf** [comment]
You don't need to match LibreNMS, you just need to name it after the OS / Firmware of the devices :)

Can you please also update the README to add this new model in: https://github.com/ytti/oxidized#supported-os-types

**Comment by sfini** [comment]
@laf 
Done in Patch-1

**Comment by laf** [comment]
@danilopopeye I've fixed the indentation, ready for a merge now if you're happy.

**Comment by sfini** [comment]
@All 

Sorry for the indentation...

**Comment by danilopopeye** [comment]
> Sorry for the indentation...

@sfini no problem at all, thanks for the new device 👏

**Pull request merged**
