### PR TITLE
Support variables for different models within groups

### PR DESCRIPTION
**Pull request by mjbnz**
## Pre-Request Checklist
- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [x] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
This pull request allows for the specifying of vars for models within groups, overriding more general vars:

```
groups:
  foo:
    models:
      arista:
        vars:
          ssh_keys: "~/.ssh/id_rsa_foo_arista"
      vyatta:
        vars:
          ssh_keys: "~/.ssh/id_rsa_foo_vyatta"
  bar:
    models:
      routeros:
        vars:
          ssh_keys: "~/.ssh/id_rsa_bar_routeros"
      vyatta:
        vars:
          ssh_keys: "~/.ssh/id_rsa_bar_vyatta"
```

### CODE REVIEW

**Comment by mjbnz** [comment]
This branch is on top of my 'rubocop-fixes' branch, hence the extra commits.

**Comment by mortzu** [comment]
Can you reflect the change in the documentation please?

**Comment by mjbnz** [comment]
> Can you reflect the change in the documentation please?

Done - however this is a less than ideal way to document this particular change, but doing it correctly requires the documentation rewrite (it should really be in a yet-to-be-created "Variables" section of the docs).

**Comment by mortzu** [comment]
Please fix the merge conflict

**Comment by mortzu** [comment]
Please fix the merge conflict (again...sorry)

**Pull request merged**
