### PR TITLE
Add haproxy example

### PR DESCRIPTION
**Pull request by denvera**

### CODE REVIEW

**Comment by laf** [comment]
Is this specific to redhat and / or debian based distros. If only one of them is it worth changing the filename to offer more clarity?

**Comment by bitfiretech** [comment]
This should apply to any haproxy package across distributions.

**Comment by denvera** [comment]
Hey, this should be generic across distributions, though the default/global sections are based on a default installation on Ubuntu. The backend and frontend sections are definitely applicable to any haproxy installation. Happy to rename if you deem necessary.

**Comment by laf** [comment]
> Hey, this should be generic across distributions, though the default/global sections are based on a default installation on Ubuntu. The backend and frontend sections are definitely applicable to any haproxy installation. Happy to rename if you deem necessary.

As in they reference file paths specific for Ubuntu? If so, could you rename it to `extra/oxidized-ubuntu.haproxy` or similar?

**Comment by denvera** [comment]
Have renamed to `oxidized-ubuntu.haproxy` to be explicit, as some of the default/global section paths may not work for other distros.

**Pull request merged**
