### PR TITLE
Add support for BOSS Extreme switches to have spaces in sys name

### PR DESCRIPTION
**Pull request by ospfbgp**
## Pre-Request Checklist

- [ ] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [ ] Tests added or adapted (try `rake test`)
- [ ] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

### CODE REVIEW

**Comment by ospfbgp** [comment]
needs more testing do not approve this pull request thanks.  Found bug. :-)

**Comment by wk** [comment]
Does the prompt in these models appear multiple times or at unexpected intervals within the output of `show running-config`? If the intention is just to remove the prompt at the end of the config, perhaps a `cut_tail` would be more suitable?

**Comment by ospfbgp** [comment]
I need to do some more testing.  I was traveling this week.  I will look into this more.  Thank you for the suggestions.  I will do some testing and debugging and see what I get.

**Comment by wk** [comment]
@ospfbgp did you have a chance to see if this can be cleaned up? I'd like to pull this in, but lacking access to a similar device or a sample of the unfiltered output, can't confirm if the suggestion above is feasible.

**Comment by mortzu** [comment]
Please process the checklist

**Pull request closed without merging**
