### PR TITLE
update prompt for aosw

### LINKED ISSUE #3151: ArubaOS8 need update propmt
there issue before
https://github.com/ytti/oxidized/issues/2237

request for https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/aosw.rb update or create a new model such like AOSW8 and update the line 14
`  comment '# '
  prompt /^([\w\(:.@-]+(\)?\s?)[#>]\s?)$/`

prompt to 
`^(\([\w\s-]+\))?\s*\[[^\]]+\]\s*[#>]\s?$`
or 
`[\w\(:.@-]+(\)?\s?)\[+[\w]+\]\s[#>]`

thanks

### PR DESCRIPTION
**Pull request by mabezi**
## Pre-Request Checklist

- [x] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [x] Tests added or adapted (try `rake test`)
- [x] Changes are reflected in the documentation
- [x] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
The aosw template no longer works with newer versions of AOS 8.

With this prompt it should work again. (At least on our devices with AOS 8 it now works).

Should close #3151

### CODE REVIEW

**Comment by robertcheramy** [comment]
Thank you for the submission. The proposed prompt is not backward compatible. I'm working on it.

**Comment by ytti** [comment]
Maybe we should make test file, that specifically loads prompt from each model, so we could put prompt unit tests in single file? It seems one of the most fragile part of models, for people who don't use exec mode, as people regularly make very poor prompts to both direction, too liberal and getting partial configs and too specific not working outside specific environemnt. 

Controlling this seems very hard, without unit test. And unlike rest of the model, it seems quite low hanging fruit to target in testing.

**Comment by robertcheramy** [comment]
The unit test is already written, will commit soon ;-)

**Comment by robertcheramy** [comment]
@mabezi - could you test the PR if it works in your setup?
If you think of prompt cases not tested in spec/model/aosw_spec.rb , feel free to add some.

**Comment by mabezi** [comment]
Works for me. Using ArubaMM-VA with AOS 8.10 and Aruba7210 with AOS 8.10

**Comment by robertcheramy** [comment]
Perfect, thank you for the quick test.

**Pull request merged**
