### PR TITLE
Procurve exclude power consumption

### PR DESCRIPTION
**Pull request by deajan**
## Pre-Request Checklist

- [X] Passes rubocop code analysis (try `rubocop --auto-correct`)
- [N/A] Tests added or adapted (try `rake test`)
- [N/A] Changes are reflected in the documentation
- [X] User-visible changes appended to [CHANGELOG.md](/CHANGELOG.md)

## Description
I recently worked on HPe 5400 series switches which work great with current oxidized, but create new versions of the configuration because of power consumption output in the configuration.

This fix replaces the actual wattage with `<removed>` so the config doesn't change.

### CODE REVIEW

**Comment by wk** [comment]
This looks good, but should move from the `:all` section into the specific section that produces the relevant output which is to be filtered.

**Comment by deajan** [comment]
Since we have both a `system-information` and a `system information` section, I thought of putting this into `:all` section in order to avoid duplicating that block for both cases.

**Comment by wk** [comment]
Are the two commands different variants to request the same information which produces the same output from different versions of devices / firmware?

**Comment by deajan** [comment]
To be honest, I don't know which devices use the `system-information` variant.
I only own devices that use `system information`.
It is my wild guess that the power consumption might also exist for the other variant.

**Comment by davama** [comment]
The power one produces the UPSs hardware info, similar to sts info cmd

**Comment by deajan** [comment]
@davama sorry what ? I dont get what you meant.

**Comment by davama** [comment]
i thought i read something else.
My bad

**Comment by wk** [comment]
This should be mostly harmless as-is. Pulling the PR. @Ultra2D  - if you could shed some light as to which of the commands is supported by which device or firmware, it might be used for those wishing to develop this model further.

**Comment by Ultra2D** [comment]
2510 and 2610 use `system-information`. 
The other models I can access do not: 2900, 2910, 3800 (and 5400).

The output is the same.

**Pull request merged**
