### PR TITLE
Fixes #1699 by not including all default values (with show full-confi…

### LINKED ISSUE #1699: Fortigate issue - gathering configuration
Hey!

I have just started using Oxidized, awesome software by the way :) I have a problem with gathering configuration from one of our Fortigate firewalls. I get the following in Oxidized log.

WARN -- : <IP-Address> raised Errno::EPIPE with msg "Broken pipe - send(2)"
WARN -- : <IP-Address> raised Timeout::Error with msg "execution expired"

The Fortigate i'm trying to gather configuration from is our datacenter firewall with several VDOMs and many lines. I have no issues with other Fortigates that have less configuration than our DC.
When i had issues in lab with Fortigate i could solve it by increasing the timeout value and i have tried up to 600 with our datacenter firewall without luck.  I have never seen the Broken Pipe message before.

If i SSH from the Oxidized server to the firewall i can run show full-configuration | grep . without any timeouts.

Does anyone have ideas on how this can be solved? Or suggestions on what i can do?

The following is our current Oxidized configuration, Oxidized is fed from LibreNMS.(I have indentation in the config file on the server)

```yaml
---
model: cisco
resolve_dns: true
interval: 86400
use_syslog: false
log: "/root/.config/oxidized/logs/log"
debug: false
threads: 30
timeout: 240
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
next_adds_job: false
vars:
  remove_secret: true
models: {}
groups: {}
pid: "/root/.config/oxidized/pid"
crash:
  directory: "/root/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
    single_repo: true
    user: XXXX
    email: XXXXXXXX
    repo: "/opt/oxidized/data/devices.git"
source:
  default: http
  csv:
    file: "/root/.config/oxidized/devices.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
    gpg: false
  http:
    url: http://127.0.0.1/api/v0/oxidized
    secure: false
    map:
      name: hostname
      model: os
    headers:
      X-Auth-Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
model_map:
  nexus: nxos
  asr: iosxr
  fortigate: fortios
```

### PR DESCRIPTION
**Pull request by jforeman**
…guration). Fixes the invariable timeout in my setup.

## Description
Shows the config instead of full config which contains extraneous amounts of default data and causes timeouts.

Closes issue #1699

### CODE REVIEW

**Comment by robertcheramy** [comment]
@jforeman - could you add the change in the CHANGELOG.md? As we change the behaviour of the model, our users should know it ;-)

**Comment by jforeman** [comment]
@robertcheramy done, but looks like I somehow created a conflict.

**Comment by jforeman** [comment]
@aschaber1, @ytti If this change is a concern, I'd be open to working with you to troubleshoot why the full-configuration output is breaking, but it's definitely not just happening to me. Thanks!

**Comment by robertcheramy** [comment]
The way to backup config as in this PR is the expected behavior. It backups the configutation the same way as you would get it from the GUI.
As an example. the configuration for "port1" before the PR:
```
config system interface
    edit "port1"
        set vdom "root"
        set vrf 0
        set fortilink disable
        set mode static
        set dhcp-relay-interface-select-method auto
        set dhcp-relay-service disable
        set ip 192.168.129.8 255.255.255.0
        set allowaccess ping https ssh http fgfm
        set fail-detect disable
        set pptp-client disable
        set arpforward enable
        set broadcast-forward disable
        set bfd global
        set l2forward disable
        set icmp-send-redirect enable
        set icmp-accept-redirect enable
        set reachable-time 30000
        set vlanforward disable
        set stpforward disable
        set ips-sniffer-mode disable
        set ident-accept disable
        set ipmac disable
        set subst disable
(...)
```
And The same Configuration after the PR (and also when doing a configuration backup through GUI):
```
config system interface
    edit "port1"
        set vdom "root"
        set ip 192.168.129.8 255.255.255.0
        set allowaccess ping https ssh http fgfm
        set type physical
        set snmp-index 1
    next
```

This is a good PR, I tested it and I recommend a merge.

**Pull request merged**
